// server.js
require("./initSync");
require("dotenv").config();
const express = require("express");
const cors = require("cors");
const path = require("path");
const fs = require("fs");
const http = require("http");
const socketIo = require("socket.io");
const pool = require("./db");
const storage = require('./cloudinaryStorage');
const { setupChatHandlers } = require('./src/utils/ChatHandlers.js');
const authRoutes = require('./src/routes/auth');
const vexaAccountSsoRoutes = require('./src/routes/vexaAccountSso');
const securityRoutes = require('./src/routes/securityRoutes');
const userRoutes = require('./src/routes/userRoutes');
const walletRoutes = require('./src/routes/walletRoutes');
const transferRoutes = require('./src/routes/transferRoutes');
const depositRoutes = require('./src/routes/depositRoutes');
const withdrawalRoutes = require('./src/routes/withdrawalRoutes');
const tradeRoutes = require('./src/routes/tradeRoutes');
const fundsRoutes = require('./src/routes/fundsRoutes');
const loanRoutes = require('./src/routes/loanRoutes');
const adminRoutes = require('./src/routes/adminRoutes');
const assetOperationsRoutes = require('./src/routes/assetOperationsRoutes');
const legalRoutes = require('./src/routes/legalRoutes');
const supportRoutes = require('./src/routes/supportRoutes');
const jointAccountRoutes = require('./src/routes/jointAccountRoutes');
const marketRoutes = require('./src/routes/marketRoutes');
const convertRoutes = require('./src/routes/convertRoutes');
const employeeRoutes = require("./employeeRoutes");
const newsRoutes = require("./newsRoutes");
const maintenanceRoutes = require("./maintenanceRoutes");
const adminFundRoutes = require("./adminFundRoutes");
const adminNetworkRoutes = require("./adminNetworkRoutes");
const overrideFundsPlans = require("./overrideFundsPlans");
const adminNotificationRoutes = require('./src/routes/adminNotifications');
const chatRoutes = require('./src/routes/chatRoutes');
const app = express();
const PORT = process.env.PORT || 5000;
const DB_NAME = process.env.DB_NAME;
const allowedOrigins = [process.env.CLIENT_ORIGIN,process.env.FRONTEND_USER_URL,process.env.FRONTEND_ADMIN_URL,process.env.FRONTEND_EMPLOYEEMONITOR_URL,"http://localhost:5173","http://localhost:5174","http://localhost:3000","https://vexatrade-6nhs.onrender.com","https://www.vexatrade-v.2bd.net","https://vexatrade-v.2bd.net","https://vexatrade-admin-n36m.onrender.com","https://admin.vexatrade-v.2bd.net","https://vexatrade-all-adminmonitor-user-activity.onrender.com","https://employee-admin-monitor-vexatrade.onrender.com","https://vexatrade-5ycu.onrender.com","https://vexastore.onrender.com","https://vexastore-admin.onrender.com","https://www.vexastore.2bd.net","https://vexastore.2bd.net","https://api-vexastore.onrender.com","https://api-vexaaccount.onrender.com"].filter(Boolean);
const corsOptions={origin(origin,callback){if(!origin||allowedOrigins.includes(origin))return callback(null,true);console.log("Blocked by CORS:",origin);return callback(new Error('CORS not allowed'));},credentials:true,methods:["GET","POST","PUT","PATCH","DELETE","OPTIONS"],allowedHeaders:["Origin","X-Requested-With","Content-Type","Accept","Authorization"]};
app.use(cors(corsOptions));app.options(/.*/,cors(corsOptions));app.use(express.json({limit:"10mb"}));app.use(express.urlencoded({extended:true}));
const uploadDirs=["uploads","uploads/deposits","uploads/qrcodes","uploads/kyc","uploads/profiles","uploads/legal","uploads/qr_codes"];for(const dir of uploadDirs){const fullPath=path.join(__dirname,dir);if(!fs.existsSync(fullPath))fs.mkdirSync(fullPath,{recursive:true});}app.use("/uploads",express.static(path.join(__dirname,"uploads")));
const server=http.createServer(app);const io=socketIo(server,{cors:{origin:allowedOrigins,credentials:true,methods:["GET","POST","PUT","DELETE"]},transports:['websocket','polling']});setupChatHandlers(io);app.set('io',io);
app.use('/api/auth',authRoutes);
app.use('/api/auth/vexaaccount',vexaAccountSsoRoutes);
app.use('/api',securityRoutes);
app.use('/api/chat',require('./src/middleware/auth').authUser,chatRoutes);
app.use('/api',userRoutes);app.use('/api',walletRoutes);app.use('/api',transferRoutes);app.use('/api',depositRoutes);app.use('/api',withdrawalRoutes);app.use('/api',tradeRoutes);app.use('/api',fundsRoutes);app.use('/api',loanRoutes);app.use('/api',adminRoutes);app.use('/api',assetOperationsRoutes);app.use('/api',legalRoutes);app.use('/api',supportRoutes);app.use('/api',jointAccountRoutes);app.use('/api',marketRoutes);app.use('/api',convertRoutes);app.use("/api/funds/plans",overrideFundsPlans);app.use("/api/admin/network-verification-settings",adminNetworkRoutes);app.use("/api/admin/fund-rules",adminFundRoutes);app.use("/api/employee",employeeRoutes);app.use("/api/news",newsRoutes);app.use("/api/maintenance",maintenanceRoutes);app.use('/api/admin',adminNotificationRoutes);
app.get('/api/health',async(req,res)=>{try{const connection=await pool.getConnection();await connection.ping();connection.release();res.json({success:true,message:"VexaTrade backend running",database:DB_NAME});}catch(_){res.status(500).json({success:false,message:"Database connection failed"});}});app.get('/',(req,res)=>res.json({success:true,message:"VexaTrade backend running"}));app.use((req,res)=>req.path.startsWith("/api/")?res.status(404).json({success:false,message:"API route not found"}):res.status(404).send("Not found"));app.use((err,req,res,next)=>{console.error("Server error:",err);const message=process.env.NODE_ENV==='production'?"Internal server error":(err.message||"Internal server error");res.status(err.status||500).json({success:false,message});});server.listen(PORT,async()=>{try{const connection=await pool.getConnection();await connection.ping();connection.release();console.log(`✅ VexaTrade backend running on port ${PORT}`);console.log(`✅ MySQL connected successfully`);console.log(`✅ Database: ${DB_NAME}`);console.log(`✅ WebSocket: ws://localhost:${PORT}`);console.log(`✅ Allowed origins: ${allowedOrigins.length} domains`);}catch(error){console.error("❌ MySQL connection failed:",error.message);}});module.exports={app,server,io};