import { useEffect,useMemo,useState } from "react";
import { CheckCircle2, ShieldCheck, TrendingDown, TrendingUp } from "lucide-react";
import { digitalOptionsApi,userApi,marketApi } from "../../../services/api";
const MATURITIES=[["30m","30 Minutes"],["1h","1 Hour"],["24h","24 Hours"],["30d","30 Days"],["1y","1 Year"]];
const PAIRS=["BTCUSDT","ETHUSDT"];
export default function DigitalOptionsTradePage(){
 const [pair,setPair]=useState("BTCUSDT"),[timeframe,setTimeframe]=useState("30m"),[direction,setDirection]=useState("CALL"),[stake,setStake]=useState(""),[strike,setStrike]=useState(""),[balance,setBalance]=useState(0),[price,setPrice]=useState(0),[settings,setSettings]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const token=localStorage.getItem("userToken")||localStorage.getItem("token")||"";
 useEffect(()=>{let live=true;const load=async()=>{try{const [s,w,m]=await Promise.all([digitalOptionsApi.settings(token),userApi.getWalletSummary(token),marketApi.price(pair)]);if(!live)return;setSettings(s.data?.data||s.data);const d=w.data?.data||w.data||{};setBalance(Number(d?.assets?.USDT?.available_balance??d?.available_balance??0));setPrice(Number(m.data?.price??m.data?.data?.price??0));}catch(e){if(live)setError(e?.response?.data?.message||"Unable to load trading data.")}};load();const id=setInterval(load,2000);return()=>{live=false;clearInterval(id)}},[pair,token]);
 const payout=Number(settings?.payout_rate??88),estimated=Number(stake||0)*payout/100;
 const submit=async()=>{if(!Number(stake)||Number(stake)<=0)return setError("Enter a valid USDT stake.");if(Number(stake)>balance)return setError("Insufficient available USDT balance.");setBusy(true);setError("");setMessage("");try{const r=await digitalOptionsApi.place({pair,direction,timeframeCode:timeframe,stake:Number(stake),strikePrice:Number(strike)||undefined},token);setMessage(`Order #${r.data?.data?.id} submitted. Stake moved to pending balance.`);setStake("");}catch(e){setError(e?.response?.data?.message||"Order submission failed.")}finally{setBusy(false)}};
 return <div className="space-y-4">
  <section className="rounded-[28px] border border-violet-300/15 bg-gradient-to-br from-violet-300/10 via-[#0a0e1a] to-[#050812] p-5">
   <div className="flex flex-wrap items-end justify-between gap-3"><div><div className="text-[9px] font-bold tracking-[.25em] text-violet-300">DIGITAL OPTIONS · ORDER TERMINAL</div><h1 className="mt-1 text-xl font-bold">Create a defined-maturity contract</h1><p className="mt-1 text-[10px] leading-5 text-slate-400">Configure each field in order. Your existing account balance and connected Digital Options API remain authoritative.</p></div><div className="rounded-2xl border border-emerald-300/15 bg-emerald-300/5 px-4 py-3 text-right"><div className="text-[8px] text-slate-500">AVAILABLE USDT</div><div className="text-xl font-bold text-emerald-300">{balance.toFixed(2)}</div></div></div>
  </section>
  <section className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-4 sm:p-5">
   <div className="grid gap-5 lg:grid-cols-[1fr_330px]">
    <div className="space-y-5">
     <Field n="01" title="Market"><div className="grid grid-cols-2 gap-2">{PAIRS.map(x=><button key={x} onClick={()=>setPair(x)} className={`min-h-12 rounded-xl border text-xs font-bold transition ${pair===x?"border-violet-300/25 bg-violet-300/10 text-violet-200":"border-white/10 text-slate-400 hover:border-white/20"}`}>{x}</button>)}</div></Field>
     <Field n="02" title="Maturity"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{MATURITIES.map(([v,l])=><button key={v} onClick={()=>setTimeframe(v)} className={`min-h-12 rounded-xl border px-2 text-[10px] font-bold ${timeframe===v?"border-violet-300/25 bg-violet-300/10 text-violet-200":"border-white/10 text-slate-400"}`}>{l}</button>)}</div></Field>
     <Field n="03" title="Barrier / strike"><div className="grid gap-2 sm:grid-cols-2"><div className="rounded-xl border border-white/10 bg-[#050812] p-3"><div className="text-[8px] text-slate-500">CURRENT LIVE PRICE</div><div className="mt-1 text-base font-bold">{price?price.toLocaleString(undefined,{maximumFractionDigits:8}):"—"} <span className="text-[9px] text-slate-600">USDT</span></div></div><input value={strike} onChange={e=>setStrike(e.target.value)} placeholder="Blank = current price" inputMode="decimal" className="w-full rounded-xl border border-white/10 bg-[#050812] p-3 text-sm text-white outline-none focus:border-violet-300/30"/></div></Field>
     <Field n="04" title="Direction"><div className="grid grid-cols-2 gap-2"><button onClick={()=>setDirection("CALL")} className={`min-h-24 rounded-2xl border p-4 text-left ${direction==="CALL"?"border-emerald-300/25 bg-emerald-400/10":"border-white/10"}`}><TrendingUp size={19} className="text-emerald-300"/><b className="mt-2 block text-sm">CALL</b><span className="text-[9px] text-slate-500">Position for an upward outcome relative to the barrier.</span></button><button onClick={()=>setDirection("PUT")} className={`min-h-24 rounded-2xl border p-4 text-left ${direction==="PUT"?"border-rose-300/25 bg-rose-400/10":"border-white/10"}`}><TrendingDown size={19} className="text-rose-300"/><b className="mt-2 block text-sm">PUT</b><span className="text-[9px] text-slate-500">Position for a downward outcome relative to the barrier.</span></button></div></Field>
     <Field n="05" title="USDT stake"><div className="relative"><input value={stake} onChange={e=>setStake(e.target.value.replace(/[^0-9.]/g,""))} placeholder="0.00" inputMode="decimal" className="w-full rounded-2xl border border-white/10 bg-[#050812] p-4 pr-20 text-xl font-bold text-white outline-none focus:border-violet-300/30"/><span className="pointer-events-none absolute right-4 top-1/2 -translate-y-1/2 text-xs text-slate-600">USDT</span></div><div className="mt-2 grid grid-cols-4 gap-1.5">{[25,50,75,100].map(p=><button key={p} onClick={()=>setStake((balance*p/100).toFixed(2))} className="rounded-lg border border-white/10 py-2 text-[8px] font-bold text-slate-400 hover:border-violet-300/20">{p===100?"MAX":p+"%"}</button>)}</div></Field>
    </div>
    <aside className="h-fit rounded-2xl border border-white/10 bg-[#050812] p-4 lg:sticky lg:top-24"><div className="text-[9px] uppercase tracking-wider text-slate-500">Order summary</div><div className="mt-3 space-y-2.5 text-xs"><Row l="Market" v={pair}/><Row l="Maturity" v={MATURITIES.find(x=>x[0]===timeframe)?.[1]||timeframe}/><Row l="Direction" v={direction}/><Row l="Strike" v={strike||"Current market"}/><Row l="Stake" v={Number(stake||0).toFixed(2)+" USDT"}/><Row l="Configured payout" v={payout.toFixed(2)+"%"}/><div className="border-t border-white/10 pt-2"><Row l="Estimated profit" v={estimated.toFixed(2)+" USDT"} green/></div></div><div className="mt-4 rounded-xl border border-cyan-300/10 bg-cyan-300/5 p-3 text-[9px] leading-4 text-slate-500"><ShieldCheck size={13} className="mb-1 text-cyan-300"/>Submission validates available USDT, transaction authorization and the existing Digital Options settlement flow.</div>{error&&<div className="mt-3 rounded-xl border border-rose-300/15 bg-rose-400/10 p-3 text-[9px] text-rose-300">{error}</div>}{message&&<div className="mt-3 rounded-xl border border-emerald-300/15 bg-emerald-400/10 p-3 text-[9px] text-emerald-300"><CheckCircle2 size={13} className="mb-1"/>{message}</div>}<button disabled={busy||!stake||Number(stake)<=0} onClick={submit} className="mt-4 w-full rounded-2xl bg-violet-300 py-3.5 text-xs font-bold text-[#12031b] disabled:opacity-35">{busy?"Submitting…":"Confirm & Submit Digital Option"}</button></aside>
   </div>
  </section>
 </div>;
}
function Field({n,title,children}){return <div><div className="mb-2 flex items-center gap-2"><span className="rounded-md bg-violet-300/10 px-1.5 py-1 text-[7px] font-bold text-violet-200">{n}</span><span className="text-[10px] font-bold text-slate-300">{title}</span></div>{children}</div>}
function Row({l,v,green}){return <div className="flex items-center justify-between gap-3"><span className="text-slate-600">{l}</span><b className={green?"text-emerald-300":"text-slate-200"}>{v}</b></div>}
