import { useEffect,useState } from "react";
import { RefreshCw,Save,ShieldCheck,SlidersHorizontal } from "lucide-react";
import { adminApi,getApiErrorMessage } from "../../services/api";
import useToast from "../../components/ToastNotification";
const token=()=>localStorage.getItem("adminToken")||localStorage.getItem("admin_token")||"";
export default function AdminSpotTradePage(){
 const t=token(),{addToast}=useToast(),[form,setForm]=useState({enabled:true,min:"10",max:"100000",slippage:"100"}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[refreshing,setRefreshing]=useState(false);
 async function load(initial){if(initial)setLoading(true);else setRefreshing(true);try{const r=await adminApi.getSpotTradeSettings(t),d=r.data?.data||{};setForm({enabled:d.trading_enabled!==false,min:String(d.min_order_usdt??10),max:String(d.max_order_usdt??100000),slippage:String(d.max_slippage_bps??100)})}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setLoading(false);setRefreshing(false)}}
 useEffect(()=>{load(true)},[t]);const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 async function save(e){e.preventDefault();const min=Number(form.min),max=Number(form.max),slip=Number(form.slippage);if(!Number.isFinite(min)||min<=0||!Number.isFinite(max)||max<=min||!Number.isFinite(slip)||slip<=0||slip>10000)return addToast("Check minimum, maximum and slippage limits.","error");setSaving(true);try{await adminApi.updateSpotTradeSettings({trading_enabled:form.enabled,min_order_usdt:min,max_order_usdt:max,max_slippage_bps:slip},t);addToast("Spot / Long-Term controls saved.","success");await load(true)}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setSaving(false)}}
 if(loading)return <div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-5 text-sm text-slate-300">Loading Spot / Long-Term controls...</div>;
 return <div className="space-y-5"><section className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-5"><div className="text-[10px] uppercase tracking-[0.3em] text-cyan-300">Trading Control Center</div><h1 className="mt-1 text-2xl font-bold text-white">Spot / Long-Term Trade</h1><p className="mt-2 text-sm text-slate-500">Independent controls for the user Spot terminal. Short-Term Trade Rules remain separate and untouched.</p></section>
 <form onSubmit={save} className="space-y-4 rounded-3xl border border-white/10 bg-[#0a0e1a] p-5"><label className="flex items-center justify-between rounded-2xl bg-[#050812] p-4"><span><b className="block text-sm">Trading enabled</b><span className="text-[10px] text-slate-500">Master switch for new Spot orders.</span></span><input type="checkbox" checked={form.enabled} onChange={e=>set("enabled",e.target.checked)} className="h-5 w-5"/></label>
 <div className="grid gap-3 md:grid-cols-3"><label className="rounded-2xl bg-[#050812] p-3"><span className="text-[10px] text-slate-500">Minimum order (USDT)</span><input type="number" min="0.01" step="0.01" value={form.min} onChange={e=>set("min",e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0a0e1a] px-3 py-3 text-sm text-white"/></label><label className="rounded-2xl bg-[#050812] p-3"><span className="text-[10px] text-slate-500">Maximum order (USDT)</span><input type="number" min="0.01" step="0.01" value={form.max} onChange={e=>set("max",e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0a0e1a] px-3 py-3 text-sm text-white"/></label><label className="rounded-2xl bg-[#050812] p-3"><span className="text-[10px] text-slate-500">Max review slippage (bps)</span><input type="number" min="1" max="10000" step="1" value={form.slippage} onChange={e=>set("slippage",e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-[#0a0e1a] px-3 py-3 text-sm text-white"/><span className="mt-1 block text-[9px] text-slate-600">100 bps = 1%. The backend enforces this.</span></label></div>
 <div className="grid gap-3 md:grid-cols-2"><div className="rounded-2xl border border-cyan-400/10 bg-cyan-400/5 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-cyan-300"><SlidersHorizontal size={15}/>Live execution controls</div><p className="mt-2 text-[10px] leading-4 text-slate-500">Every order is rechecked against the live server price, balance, configured limits and idempotency key. No synthetic price is generated.</p></div><div className="rounded-2xl border border-emerald-400/10 bg-emerald-400/5 p-4"><div className="flex items-center gap-2 text-xs font-semibold text-emerald-300"><ShieldCheck size={15}/>Security & settlement</div><p className="mt-2 text-[10px] leading-4 text-slate-500">Spot orders use transaction-security middleware and settle through the asset ledger.</p></div></div>
 <div className="flex gap-2"><button type="button" onClick={()=>load(false)} disabled={refreshing||saving} className="rounded-xl border border-white/10 px-4 py-3 text-xs disabled:opacity-40"><RefreshCw size={14} className={refreshing?"inline mr-1 animate-spin":"inline mr-1"}/>Refresh</button><button disabled={saving} className="flex-1 rounded-xl bg-cyan-400 py-3 text-sm font-bold text-black disabled:opacity-40"><Save size={15} className="mr-1 inline"/>{saving?"Saving...":"Save Controls"}</button></div></form></div>;
}