import {useEffect,useState} from "react";
import {CheckCircle2,Plus,RefreshCw,Save,Trash2,Play} from "lucide-react";
import {adminApi,getApiErrorMessage} from "../../services/api";
import useToast from "../../components/ToastNotification";
const token=()=>localStorage.getItem("adminToken")||localStorage.getItem("admin_token")||"";
const blank={name:"",min_order_usdt:"10",max_order_usdt:"100000",max_slippage_bps:"100",trading_fee_bps:"0",quote_ttl_seconds:"15",max_orders_per_day:"0",pnl_enabled:true,pnl_refresh_seconds:"5",win_threshold_bps:"1",loss_threshold_bps:"1",realized_pnl_on_sell:true,trading_enabled:true,buy_enabled:true,sell_enabled:true,supported_pairs:"BTCUSDT,ETHUSDT,SOLUSDT,BNBUSDT,XRPUSDT,DOGEUSDT,ADAUSDT,AVAXUSDT,LINKUSDT",maintenance_message:"",status:"draft"};
export default function AdminSpotSettlementRulesPage(){
 const t=token(),{addToast}=useToast();const[rules,setRules]=useState([]),[form,setForm]=useState(blank),[editing,setEditing]=useState(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const load=async()=>{setLoading(true);try{const r=await adminApi.getSpotSettlementRules(t);setRules(Array.isArray(r.data?.data)?r.data.data:[])}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 const set=(k,v)=>setForm(p=>({...p,[k]:v}));
 const save=async e=>{e.preventDefault();setBusy(true);try{const payload={...form,min_order_usdt:Number(form.min_order_usdt),max_order_usdt:Number(form.max_order_usdt),max_slippage_bps:Number(form.max_slippage_bps),trading_fee_bps:Number(form.trading_fee_bps),quote_ttl_seconds:Number(form.quote_ttl_seconds),max_orders_per_day:Number(form.max_orders_per_day),pnl_refresh_seconds:Number(form.pnl_refresh_seconds),win_threshold_bps:Number(form.win_threshold_bps),loss_threshold_bps:Number(form.loss_threshold_bps),trading_enabled:!!form.trading_enabled,buy_enabled:!!form.buy_enabled,sell_enabled:!!form.sell_enabled,supported_pairs:form.supported_pairs,maintenance_message:form.maintenance_message};if(editing)await adminApi.updateSpotSettlementRule(editing,payload,t);else await adminApi.createSpotSettlementRule(payload,t);addToast(editing?"Settlement rule updated":"Settlement rule created","success");setForm(blank);setEditing(null);await load()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setBusy(false)}};
 const edit=r=>{setEditing(r.id);setForm({name:r.name,min_order_usdt:String(r.min_order_usdt),max_order_usdt:String(r.max_order_usdt),max_slippage_bps:String(r.max_slippage_bps),trading_fee_bps:String(r.trading_fee_bps),quote_ttl_seconds:String(r.quote_ttl_seconds),max_orders_per_day:String(r.max_orders_per_day),pnl_enabled:!!r.pnl_enabled,pnl_refresh_seconds:String(r.pnl_refresh_seconds),win_threshold_bps:String(r.win_threshold_bps ?? 1),loss_threshold_bps:String(r.loss_threshold_bps ?? 1),realized_pnl_on_sell:!!r.realized_pnl_on_sell,trading_enabled:!!r.trading_enabled,buy_enabled:!!r.buy_enabled,sell_enabled:!!r.sell_enabled,supported_pairs:r.supported_pairs||blank.supported_pairs,maintenance_message:r.maintenance_message||"",status:r.status})};
 const activate=async id=>{if(busy)return;setBusy(true);try{await adminApi.activateSpotSettlementRule(id,t);addToast("Settlement rule activated and copied to live Spot controls","success");await load()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setBusy(false)}};
 const remove=async id=>{if(busy)return;setBusy(true);try{await adminApi.deleteSpotSettlementRule(id,t);addToast("Draft settlement rule deleted","success");await load()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setBusy(false)}};
 return <div className="space-y-3 text-xs">
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3 sm:p-4"><div className="text-[9px] uppercase tracking-[0.25em] text-cyan-300">Spot / Long-Term · Rules</div><h1 className="mt-1 text-base font-bold text-white sm:text-lg">Settlement Rule Profiles</h1><p className="mt-1 text-[9px] leading-4 text-slate-500">Create reusable objective market-settlement profiles. Activating one updates the live Spot controls. WIN/LOSS is calculated from verified execution price versus the user asset cost basis; admins control thresholds, not individual outcomes.</p></section>
  <form onSubmit={save} className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3 sm:p-4">
   <div className="mb-2 flex items-center justify-between"><b className="text-[11px] text-white">{editing?"Edit profile":"Create profile"}</b>{editing&&<button type="button" onClick={()=>{setEditing(null);setForm(blank)}} className="text-[9px] text-slate-500">Cancel edit</button>}</div>
   <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
    {[["name","Profile name"],["min_order_usdt","Min USDT"],["max_order_usdt","Max USDT"],["max_slippage_bps","Slippage bps"],["trading_fee_bps","Fee bps"],["quote_ttl_seconds","Quote TTL sec"],["max_orders_per_day","Daily orders"],["pnl_refresh_seconds","P/L refresh sec"],["win_threshold_bps","WIN threshold bps"],["loss_threshold_bps","LOSS threshold bps"]].map(([k,l])=><label key={k} className="rounded-xl bg-[#050812] p-2"><span className="text-[8px] text-slate-500">{l}</span><input value={form[k]} onChange={e=>set(k,e.target.value)} inputMode={k==="name"?"text":"decimal"} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a0e1a] px-2 py-2 text-[10px] text-white outline-none focus:border-cyan-400"/></label>)}
    <label className="col-span-2 rounded-xl bg-[#050812] p-2 sm:col-span-4"><span className="text-[8px] text-slate-500">Supported pairs · comma separated</span><input value={form.supported_pairs} onChange={e=>set("supported_pairs",e.target.value.toUpperCase())} placeholder="BTCUSDT,ETHUSDT,SOLUSDT" className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a0e1a] px-2 py-2 text-[10px] text-white outline-none focus:border-cyan-400"/></label>
    <label className="col-span-2 rounded-xl bg-[#050812] p-2 sm:col-span-4"><span className="text-[8px] text-slate-500">Maintenance / user-facing message</span><input value={form.maintenance_message} onChange={e=>set("maintenance_message",e.target.value)} placeholder="Optional message when Spot is disabled" maxLength={255} className="mt-1 w-full rounded-lg border border-white/10 bg-[#0a0e1a] px-2 py-2 text-[10px] text-white outline-none focus:border-cyan-400"/></label>
   </div>
   <div className="mt-2 grid grid-cols-2 gap-2 sm:grid-cols-5"><label className="flex items-center justify-between rounded-xl bg-[#050812] p-2.5 text-[9px]">Spot enabled<input type="checkbox" checked={form.trading_enabled} onChange={e=>set("trading_enabled",e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl bg-[#050812] p-2.5 text-[9px]">Buy enabled<input type="checkbox" checked={form.buy_enabled} onChange={e=>set("buy_enabled",e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl bg-[#050812] p-2.5 text-[9px]">Sell enabled<input type="checkbox" checked={form.sell_enabled} onChange={e=>set("sell_enabled",e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl bg-[#050812] p-2.5 text-[9px]">Live P/L<input type="checkbox" checked={form.pnl_enabled} onChange={e=>set("pnl_enabled",e.target.checked)}/></label><label className="flex items-center justify-between rounded-xl bg-[#050812] p-2.5 text-[9px]">Realize on sell<input type="checkbox" checked={form.realized_pnl_on_sell} onChange={e=>set("realized_pnl_on_sell",e.target.checked)}/></label></div>
   <div className="mt-2 flex gap-2"><button disabled={busy} className="flex-1 rounded-xl bg-cyan-400 py-2.5 text-[10px] font-bold text-black disabled:opacity-40"><Save size={13} className="mr-1 inline"/>{editing?"Update profile":"Create profile"}</button><button type="button" disabled={busy} onClick={()=>{setEditing(null);setForm(blank)}} className="rounded-xl border border-white/10 px-3 py-2.5 text-[10px]">Reset</button></div>
  </form>
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex items-center justify-between"><b className="text-[11px]">Saved profiles</b><button onClick={load} disabled={loading||busy} className="text-cyan-300"><RefreshCw size={13} className={loading?"animate-spin":""}/></button></div><div className="mt-2 grid gap-2 md:grid-cols-2 xl:grid-cols-3">{rules.map(r=><article key={r.id} className="rounded-xl border border-white/5 bg-[#050812] p-2.5"><div className="flex items-start justify-between gap-2"><div><b className="text-[10px] text-white">{r.name}</b><div className="mt-0.5 text-[8px] text-slate-600">#{r.id} · market_execution · public market</div></div><span className={r.status==="active"?"rounded-full bg-emerald-400/10 px-2 py-1 text-[8px] text-emerald-300":"rounded-full bg-white/5 px-2 py-1 text-[8px] text-slate-500"}>{r.status}</span></div><div className="mt-2 grid grid-cols-2 gap-1 text-[8px]"><div className="rounded-lg bg-[#0a0e1a] p-2">Min / Max <b className="block text-white">{r.min_order_usdt} / {r.max_order_usdt}</b></div><div className="rounded-lg bg-[#0a0e1a] p-2">Fee / Slip <b className="block text-white">{r.trading_fee_bps} / {r.max_slippage_bps} bps</b></div><div className="rounded-lg bg-[#0a0e1a] p-2">Quote TTL <b className="block text-white">{r.quote_ttl_seconds}s</b></div><div className="rounded-lg bg-[#0a0e1a] p-2">WIN / LOSS <b className="block text-white">{r.win_threshold_bps ?? 1} / {r.loss_threshold_bps ?? 1} bps</b></div><div className="rounded-lg bg-[#0a0e1a] p-2">Daily limit <b className="block text-white">{r.max_orders_per_day||"Unlimited"}</b></div><div className="col-span-2 rounded-lg bg-[#0a0e1a] p-2">Pairs <b className="block truncate text-white">{r.supported_pairs||"Configured in live settings"}</b></div></div><div className="mt-2 grid grid-cols-3 gap-1"><button onClick={()=>edit(r)} className="rounded-lg border border-white/10 py-1.5 text-[8px]">Edit</button><button disabled={busy||r.status==="active"} onClick={()=>activate(r.id)} className="rounded-lg bg-emerald-400/10 py-1.5 text-[8px] text-emerald-300 disabled:opacity-30"><Play size={10} className="mr-1 inline"/>Activate</button><button disabled={busy||r.status==="active"} onClick={()=>remove(r.id)} className="rounded-lg border border-red-400/10 py-1.5 text-[8px] text-red-300 disabled:opacity-30"><Trash2 size={10} className="mr-1 inline"/>Delete</button></div></article>)}</div>{!rules.length&&!loading&&<div className="p-5 text-center text-[9px] text-slate-600"><Plus size={16} className="mx-auto mb-1"/>No profiles yet.</div>}</section>
  <div className="flex items-start gap-2 rounded-xl border border-amber-400/10 bg-amber-400/5 p-2.5 text-[8px] leading-4 text-slate-500"><CheckCircle2 size={12} className="mt-0.5 shrink-0 text-amber-300"/>Spot settlement remains objective: live public market execution, configured limits/fees/slippage, and auditable receipts. WIN/LOSS thresholds classify realized P/L on sell; there is no per-user outcome override.</div>
 </div>
}
