import { useEffect,useMemo,useState } from "react";
import { useSearchParams,useNavigate } from "react-router-dom";
import { CheckCircle2,ExternalLink,RefreshCw,Save,ShieldCheck,UserSearch,XCircle } from "lucide-react";
import { adminApi,getApiErrorMessage } from "../../services/api";
import useToast from "../../components/ToastNotification";
const emptyStep=(n)=>({stepNumber:n,title:"Verification Step "+n,description:"",coin:"USDT",network:"TRC20",verificationAddress:"",verificationMethod:"transaction_evidence",requiredAmount:"",requiredAmountDisplay:"",evidenceRequired:true,transactionHashRequired:true,receiptRequired:true});
const defaults={title:"External Wallet Verification",description:"Complete the three verification stages below to restore full VexaTrade access.",steps:[1,2,3].map(emptyStep)};
function Badge({value}){const v=String(value||"-");const tone=["completed","approved","active"].includes(v)?"border-emerald-500/20 bg-emerald-500/10 text-emerald-300":["submitted","pending","verification_processing"].includes(v)?"border-amber-500/20 bg-amber-500/10 text-amber-300":["rejected","locked"].includes(v)?"border-red-500/20 bg-red-500/10 text-red-300":"border-white/10 bg-white/[0.04] text-slate-300";return <span className={"rounded-full border px-2 py-1 text-[10px] font-semibold "+tone}>{v.replaceAll("_"," ")}</span>}
export default function AdminAccountVerificationPage(){
 const [params]=useSearchParams(),navigate=useNavigate(),token=localStorage.getItem("adminToken")||localStorage.getItem("admin_token")||"";
 const {addToast,ToastContainer}=useToast(),initialId=params.get("userId")||"";
 const [userId,setUserId]=useState(initialId),[users,setUsers]=useState([]),[workflow,setWorkflow]=useState(null),[form,setForm]=useState(defaults),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[reviewing,setReviewing]=useState(null),[finalizing,setFinalizing]=useState(false),[note,setNote]=useState("");
 const selectedUser=useMemo(()=>users.find(u=>String(u.id)===String(userId)),[users,userId]);
 async function loadUsers(){try{const r=await adminApi.getUsers(token);setUsers(r?.data?.data||r?.data?.users||[])}catch(e){addToast(getApiErrorMessage(e),"error")}}
 async function loadWorkflow(id=userId){if(!id)return;try{setLoading(true);const r=await adminApi.getAccountVerification(id,token);const w=r?.data?.data||{enabled:false,steps:[],submissions:[]};setWorkflow(w);setForm({title:w.title||defaults.title,description:w.description||defaults.description,steps:[1,2,3].map(n=>{const x=(w.steps||[]).find(s=>Number(s.step_number||s.stepNumber)===n)||emptyStep(n);return {...emptyStep(n),...x,stepNumber:n,verificationAddress:x.verification_address||x.verificationAddress||"",requiredAmount:x.required_amount??x.requiredAmount??"",requiredAmountDisplay:x.required_amount_display||x.requiredAmountDisplay||"",evidenceRequired:Number(x.evidence_required??x.evidenceRequired??1)===1,transactionHashRequired:Number(x.transaction_hash_required??x.transactionHashRequired??1)===1,receiptRequired:Number(x.receipt_required??x.receiptRequired??1)===1}})})}catch(e){setWorkflow(null);addToast(getApiErrorMessage(e),"error")}finally{setLoading(false)}}
 useEffect(()=>{void loadUsers()},[]);useEffect(()=>{if(initialId)void loadWorkflow(initialId)},[initialId]);
 function updateStep(i,key,value){setForm(p=>({...p,steps:p.steps.map((s,idx)=>idx===i?{...s,[key]:value}:s)}))}
 async function save(){try{setSaving(true);await adminApi.saveAccountVerification(userId,{enabled:true,title:form.title,description:form.description,steps:form.steps},token);addToast("Verification workflow saved and enabled.","success");await loadWorkflow()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setSaving(false)}}
 async function disable(){try{setSaving(true);await adminApi.saveAccountVerification(userId,{enabled:false,title:form.title,description:form.description,steps:form.steps},token);addToast("Verification requirement disabled.","success");await loadWorkflow()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setSaving(false)}}
 async function review(id,decision){try{setReviewing(id);await adminApi.reviewAccountVerification(id,{decision,note},token);setNote("");addToast(decision==="approve"?"Step approved.":"Step rejected.","success");await loadWorkflow()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setReviewing(null)}}
 async function finalReview(decision){try{setFinalizing(true);await adminApi.finalReviewAccountVerification(userId,{decision,note},token);setNote("");addToast(decision==="approve"?"Account verification approved; access restored.":"Final verification rejected.","success");await loadWorkflow()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setFinalizing(false)}}
 return <div className="space-y-5"><ToastContainer/>
 <section className="rounded-[28px] border border-white/10 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.12),transparent_22%),linear-gradient(180deg,#111827,#020617)] p-5 shadow-xl"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[10px] uppercase tracking-[.3em] text-cyan-300">Account Control</div><h1 className="mt-2 text-2xl font-bold text-white">External Wallet Verification</h1><p className="mt-2 text-xs text-slate-400">Configure three staged evidence checks for one user account. This workflow records evidence only and does not debit the financial ledger.</p></div><button onClick={()=>navigate("/admin/users")} className="rounded-xl border border-white/10 bg-white/[.04] px-3 py-2 text-xs text-white">Back to users</button></div>
 <div className="mt-4 grid gap-2 sm:grid-cols-[1fr_auto]"><div className="relative"><UserSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500" size={15}/><select value={userId} onChange={e=>{setUserId(e.target.value);if(e.target.value)void loadWorkflow(e.target.value)}} className="w-full rounded-xl border border-white/10 bg-[#050812] py-3 pl-9 pr-3 text-sm text-white"><option value="">Select user account…</option>{users.map(u=><option key={u.id} value={u.id}>{u.name||u.email||u.uid||u.id} · #{u.id}</option>)}</select></div>{userId?<button onClick={()=>loadWorkflow()} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.04] px-4 py-3 text-xs font-semibold text-white"><RefreshCw size={14} className={loading?"animate-spin":""}/>Refresh</button>:null}</div>
 {selectedUser?<div className="mt-3 rounded-xl border border-cyan-400/10 bg-cyan-500/5 px-3 py-2 text-xs text-slate-300">{selectedUser.name||"User"} · {selectedUser.email||"-"} · UID {selectedUser.uid||"-"}</div>:null}</section>
 {userId?<><section className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-4 shadow-xl"><div className="grid gap-3"><input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white" placeholder="Workflow title"/><textarea rows={3} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white" placeholder="Workflow description"/></div></section>
 {form.steps.map((s,i)=><section key={s.stepNumber} className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-4 shadow-xl"><div className="mb-4 flex items-center justify-between"><div><div className="text-[10px] uppercase tracking-[.22em] text-cyan-300">Stage {s.stepNumber}</div><h2 className="mt-1 text-base font-semibold text-white">{s.title||("Verification Step "+s.stepNumber)}</h2></div><Badge value={workflow?.steps?.find(x=>Number(x.step_number||x.stepNumber)===s.stepNumber)?.status||"pending"}/></div><div className="grid gap-3 md:grid-cols-2"><input value={s.title} onChange={e=>updateStep(i,"title",e.target.value)} placeholder="Screen title" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><input value={s.coin} onChange={e=>updateStep(i,"coin",e.target.value)} placeholder="Coin" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><input value={s.network} onChange={e=>updateStep(i,"network",e.target.value)} placeholder="Network" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><input value={s.requiredAmount} onChange={e=>updateStep(i,"requiredAmount",e.target.value)} placeholder="Required exact amount" inputMode="decimal" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><input value={s.requiredAmountDisplay} onChange={e=>updateStep(i,"requiredAmountDisplay",e.target.value)} placeholder="Amount display (optional)" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white md:col-span-2"/><input value={s.verificationAddress} onChange={e=>updateStep(i,"verificationAddress",e.target.value)} placeholder="Verification address" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white md:col-span-2"/><textarea rows={3} value={s.description} onChange={e=>updateStep(i,"description",e.target.value)} placeholder="Stage description" className="rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white md:col-span-2"/></div><div className="mt-3 flex flex-wrap gap-4 text-xs text-slate-400">{[["transactionHashRequired","Transaction hash required"],["receiptRequired","Receipt/evidence required"]].map(([k,l])=><label key={k} className="flex items-center gap-2"><input type="checkbox" checked={s[k]} onChange={e=>updateStep(i,k,e.target.checked)}/>{l}</label>)}</div></section>)}
 <div className="flex flex-col gap-2 sm:flex-row"><button disabled={saving} onClick={save} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 text-sm font-bold text-slate-950"><Save size={15}/>{saving?"Saving…":"Save & Enable Verification"}</button><button disabled={saving} onClick={disable} className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm font-semibold text-red-300">Disable Requirement</button></div>
 <section className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-4 shadow-xl"><div className="flex items-center justify-between"><div><h2 className="font-semibold text-white">Submission review</h2><p className="text-[11px] text-slate-500">Review each stage before the next stage unlocks.</p></div><Badge value={workflow?.final_review_status||"not_submitted"}/></div><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} placeholder="Admin review note (optional)" className="mt-3 w-full rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><div className="mt-3 space-y-2">{(workflow?.submissions||[]).map(sub=><div key={sub.id} className="rounded-xl border border-white/10 bg-white/[.02] p-3"><div className="flex flex-wrap items-center justify-between gap-2"><div className="text-xs font-semibold text-white">Stage {sub.step_number} · {sub.step_title}</div><Badge value={sub.status}/></div><div className="mt-2 text-[11px] text-slate-400"><div>Amount: <span className="text-slate-200">{sub.submitted_amount||sub.amount||"—"}</span></div><div>Transaction: <span className="text-slate-200">{sub.transaction_hash||"—"}</span></div>{sub.receipt_url?<a href={sub.receipt_url} target="_blank" rel="noreferrer" className="mt-1 inline-flex items-center gap-1 text-cyan-300">Open evidence <ExternalLink size={12}/></a>:null}</div>{sub.status==="submitted"?<div className="mt-3 flex gap-2"><button disabled={reviewing===sub.id} onClick={()=>review(sub.id,"approve")} className="inline-flex items-center gap-1 rounded-lg bg-emerald-500/15 px-3 py-2 text-xs text-emerald-300"><CheckCircle2 size={13}/>Approve</button><button disabled={reviewing===sub.id} onClick={()=>review(sub.id,"reject")} className="inline-flex items-center gap-1 rounded-lg bg-red-500/15 px-3 py-2 text-xs text-red-300"><XCircle size={13}/>Reject</button></div>:null}</div>)}</div><div className="mt-4 flex flex-col gap-2 sm:flex-row"><button disabled={finalizing||workflow?.final_review_status==="approved"} onClick={()=>finalReview("approve")} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-500 px-4 py-3 text-sm font-bold text-slate-950"><ShieldCheck size={15}/>{finalizing?"Processing…":"Final Approve & Restore Access"}</button><button disabled={finalizing} onClick={()=>finalReview("reject")} className="rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm font-semibold text-red-300">Final Reject</button></div></section></>
 :<div className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-8 text-center text-sm text-slate-500">Select a user account to configure verification.</div>}</div>}
