import {useEffect,useMemo,useState} from "react";
import {CheckCircle2,ExternalLink,RefreshCw,Search,XCircle,ShieldCheck,Clock3} from "lucide-react";
import {adminApi,getApiErrorMessage} from "../../services/api";
import useToast from "../../components/ToastNotification";
const token=()=>localStorage.getItem("adminToken")||localStorage.getItem("admin_token")||"";
const Badge=({value})=>{const v=String(value||"-").toLowerCase();const c=["approved","completed"].includes(v)?"border-emerald-500/20 bg-emerald-500/10 text-emerald-300":v==="submitted"?"border-amber-500/20 bg-amber-500/10 text-amber-300":v==="rejected"?"border-red-500/20 bg-red-500/10 text-red-300":"border-white/10 bg-white/[.04] text-slate-300";return <span className={"rounded-full border px-2 py-1 text-[9px] font-semibold uppercase tracking-wide "+c}>{v.replaceAll("_"," ")}</span>};
export default function AdminAccountVerificationSubmissionReviewPage(){
 const t=token(),{addToast,ToastContainer}=useToast();const[rows,setRows]=useState([]),[status,setStatus]=useState("submitted"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[reviewing,setReviewing]=useState(null),[note,setNote]=useState("");
 const load=async(showToast=false)=>{setLoading(true);try{const r=await adminApi.getAccountVerificationSubmissions({status,limit:200},t);setRows(Array.isArray(r?.data?.data)?r.data.data:[]);if(showToast)addToast("Submission review queue refreshed.","success")}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setLoading(false)}};
 useEffect(()=>{void load()},[status]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();if(!q)return rows;return rows.filter(x=>[x.name,x.email,x.uid,x.transaction_hash,x.step_title,x.network,x.coin,String(x.user_id),String(x.id)].some(v=>String(v||"").toLowerCase().includes(q)))},[rows,search]);
 const review=async(id,decision)=>{setReviewing(id);try{await adminApi.reviewAccountVerification(id,{decision,note},t);setNote("");addToast(decision==="approve"?"Stage approved and next stage unlocked.":"Stage rejected; user can resubmit this stage.","success");await load()}catch(e){addToast(getApiErrorMessage(e),"error")}finally{setReviewing(null)}};
 return <div className="space-y-3 text-xs"><ToastContainer/>
  <section className="rounded-2xl border border-white/10 bg-[radial-gradient(circle_at_top_right,rgba(34,211,238,.12),transparent_25%),#0a0e1a] p-4 sm:p-5">
   <div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div><div className="text-[9px] uppercase tracking-[.28em] text-cyan-300">Accounts · Submission Review</div><h1 className="mt-1 text-lg font-bold text-white sm:text-xl">External Wallet Verification Submission Review</h1><p className="mt-1 max-w-3xl text-[10px] leading-4 text-slate-500">One queue for every user-submitted verification stage. Review Stage 1 → Stage 2 → Stage 3 evidence, approve or reject each submitted stage, and keep the existing final account review workflow authoritative.</p></div><button onClick={()=>load(true)} disabled={loading} className="inline-flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[.03] px-3 py-2 text-[10px] font-semibold text-white"><RefreshCw size={13} className={loading?"animate-spin":""}/>Refresh</button></div>
   <div className="mt-4 grid gap-2 sm:grid-cols-[auto_auto_1fr]"><div className="grid grid-cols-3 rounded-xl bg-[#050812] p-1">{["submitted","approved","rejected"].map(x=><button key={x} onClick={()=>setStatus(x)} className={"rounded-lg px-3 py-2 text-[9px] font-bold uppercase "+(status===x?"bg-cyan-400 text-black":"text-slate-500")}>{x}</button>)}</div><div className="flex items-center gap-2 rounded-xl border border-white/10 bg-[#050812] px-3 py-2"><Clock3 size={13} className="text-cyan-300"/><span className="text-[9px] text-slate-500">{rows.length} records</span></div><div className="relative"><Search size={13} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-600"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search user, UID, transaction hash, stage…" className="w-full rounded-xl border border-white/10 bg-[#050812] py-2.5 pl-9 pr-3 text-[10px] text-white outline-none focus:border-cyan-400/30"/></div></div>
  </section>
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3 sm:p-4"><div className="mb-2 flex items-center justify-between"><div><b className="text-[11px] text-white">Stage submissions</b><div className="text-[9px] text-slate-600">Each record is tied to the live verification request and user account.</div></div><ShieldCheck size={16} className="text-cyan-300"/></div>
   <div className="space-y-2">{filtered.map(x=><article key={x.id} className="rounded-2xl border border-white/10 bg-[#050812] p-3">
    <div className="flex flex-col gap-2 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-wider text-cyan-300">Stage {x.step_number}</span><Badge value={x.status}/><Badge value={x.final_review_status}/></div><h2 className="mt-1 text-sm font-semibold text-white">{x.step_title||"Verification stage"} · {x.coin||"USDT"} {x.network||""}</h2><div className="mt-1 text-[9px] text-slate-500">{x.name||"User"} · {x.email||"-"} · UID {x.uid||x.user_id||"-"} · Submission #{x.id}</div></div><div className="text-right text-[9px] text-slate-600">{x.created_at?new Date(x.created_at).toLocaleString():"-"}</div></div>
    <div className="mt-3 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl bg-[#0a0e1a] p-2"><span className="text-[8px] text-slate-600">Submitted amount</span><b className="mt-1 block text-[10px] text-white">{x.submitted_amount??"—"} {x.coin||""}</b></div><div className="rounded-xl bg-[#0a0e1a] p-2"><span className="text-[8px] text-slate-600">Required amount</span><b className="mt-1 block text-[10px] text-white">{x.required_amount_display||x.required_amount||"—"}</b></div><div className="rounded-xl bg-[#0a0e1a] p-2"><span className="text-[8px] text-slate-600">Transaction hash</span><b className="mt-1 block truncate text-[10px] text-white">{x.transaction_hash||"—"}</b></div><div className="rounded-xl bg-[#0a0e1a] p-2"><span className="text-[8px] text-slate-600">Account state</span><b className="mt-1 block text-[10px] text-white">{x.account_status||"—"}</b></div></div>
    <div className="mt-2 flex flex-wrap items-center gap-2">{x.receipt_url?<a href={x.receipt_url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-lg border border-cyan-400/15 bg-cyan-400/5 px-3 py-2 text-[9px] text-cyan-300"><ExternalLink size={11}/>Open evidence</a>:<span className="text-[9px] text-slate-600">No evidence URL</span>}{x.evidence_note?<span className="max-w-xl truncate text-[9px] text-slate-500">Note: {x.evidence_note}</span>:null}</div>
    {x.status==="submitted"?<div className="mt-3 grid gap-2 sm:grid-cols-[1fr_auto_auto]"><input value={reviewing===x.id?note:""} onChange={e=>setNote(e.target.value)} placeholder="Review note (optional)" className="rounded-xl border border-white/10 bg-[#0a0e1a] px-3 py-2.5 text-[10px] text-white outline-none"/><button disabled={reviewing===x.id} onClick={()=>review(x.id,"approve")} className="inline-flex items-center justify-center gap-1 rounded-xl bg-emerald-400 px-4 py-2.5 text-[9px] font-bold text-black"><CheckCircle2 size={12}/>Approve Stage</button><button disabled={reviewing===x.id} onClick={()=>review(x.id,"reject")} className="inline-flex items-center justify-center gap-1 rounded-xl border border-red-400/20 bg-red-400/10 px-4 py-2.5 text-[9px] font-bold text-red-300"><XCircle size={12}/>Reject Stage</button></div>:null}
   </article>)}</div>
   {!filtered.length&&!loading?<div className="rounded-xl bg-[#050812] p-8 text-center text-[10px] text-slate-600">No {status} verification submissions match the current search.</div>:null}
  </section>
 </div>;
}