const router=require('express').Router();
const multer=require('multer');
const storage=require('../../cloudinaryStorage');
const {authUser,authAdmin}=require('../middleware/auth');
const service=require('../../services/accountVerificationService');
const {ensure}=require('../../services/accountVerificationSchema');
const upload=multer({storage,limits:{fileSize:10*1024*1024},fileFilter:(req,file,cb)=>{const ok=['image/jpeg','image/png','image/webp','application/pdf'].includes(String(file.mimetype||'').toLowerCase());if(!ok)return cb(Object.assign(new Error('Only JPG, PNG, WEBP, or PDF evidence files are allowed'),{status:400}));cb(null,true);}});
const ready=async(fn,req,res,next)=>{try{await ensure();await fn(req,res,next);}catch(e){next(e);}};
router.get('/account-verification/status',authUser,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.workflow(req.user.id)}),req,res,next));
router.post('/account-verification/steps/:stepNumber/submit',authUser,(req,res,next)=>{if(!/^([1-3])$/.test(String(req.params.stepNumber)))return res.status(400).json({success:false,message:'Verification step must be 1, 2, or 3'});next();},upload.single('receipt'),(req,res,next)=>ready(async()=>{const n=Number(req.params.stepNumber);const receipt=req.file?.path||req.file?.secure_url||req.body.receipt_url||'';res.json({success:true,data:await service.submit(req.user.id,n,{transactionHash:req.body.transaction_hash,amount:req.body.amount,receiptUrl:receipt,evidenceNote:req.body.evidence_note})});},req,res,next));
router.get('/admin/account-verification/submissions',authAdmin,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.submissionQueue({status:req.query?.status,userId:req.query?.userId,limit:req.query?.limit})}),req,res,next));\nrouter.get('/admin/account-verification/:userId',authAdmin,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.adminGet(Number(req.params.userId))}),req,res,next));
router.put('/admin/account-verification/:userId',authAdmin,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.configure(req.admin.id,Number(req.params.userId),req.body||{})}),req,res,next));
router.post('/admin/account-verification/submissions/:id/review',authAdmin,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.review(req.admin.id,Number(req.params.id),req.body?.decision,req.body?.note||'')}),req,res,next));
router.post('/admin/account-verification/:userId/final-review',authAdmin,(req,res,next)=>ready(async()=>res.json({success:true,data:await service.finalReview(req.admin.id,Number(req.params.userId),req.body?.decision,req.body?.note||'')}),req,res,next));
module.exports=router;