const router = require('express').Router();
const jwt = require('jsonwebtoken');
const pool = require('../../db');
const { register, login, verifyOtp, resendOtp, verifyEmail2fa, resendEmail2fa, verifyTwoFactor, forgotPassword, resetPassword } = require('../../services/vexaccount');

function safeEmail(email) { return String(email || '').trim().toLowerCase(); }

router.get('/test', (req,res) => res.json({ success:true, message:'Auth routes loaded successfully' }));
router.post('/check-user', async (req,res) => { try { const email=safeEmail(req.body?.email); if(!email)return res.status(400).json({success:false,exists:false,message:'Email required'}); const [rows]=await pool.execute('SELECT id, uid, name, email_verified, kyc_status, status FROM users WHERE email=? LIMIT 1',[email]); if(!rows.length)return res.json({success:true,exists:false,needsVerification:true,user:null}); const user=rows[0]; const needsVerification=Number(user.email_verified||0)!==1||String(user.kyc_status||'not_submitted').toLowerCase()!=='approved'||String(user.status||'pending').toLowerCase()!=='active'; return res.json({success:true,exists:true,needsVerification,user}); } catch(error){console.error('[check-user] failed:',error.message);return res.status(500).json({success:false,message:'Unable to check account'});} });
router.post('/sync-user', async(req,res)=>{try{const email=safeEmail(req.body?.email);if(!email)return res.status(400).json({success:false,message:'Email required'});const profile=req.body?.userData||{};const [existing]=await pool.execute('SELECT * FROM users WHERE email=? LIMIT 1',[email]);let user,isNewUser=false;if(existing.length){user=existing[0];await pool.execute(`UPDATE users SET name=COALESCE(?,name),first_name=COALESCE(?,first_name),last_name=COALESCE(?,last_name),gender=COALESCE(?,gender),date_of_birth=COALESCE(?,date_of_birth),country=COALESCE(?,country),avatar_url=COALESCE(?,avatar_url),updated_at=NOW() WHERE id=?`,[profile.name||profile.full_name||null,profile.first_name||profile.firstName||null,profile.last_name||profile.lastName||null,profile.gender||null,profile.dob||profile.date_of_birth||null,profile.country||null,profile.avatar_url||null,user.id]);}else{isNewUser=true;const [[lastUser]]=await pool.execute('SELECT id FROM users ORDER BY id DESC LIMIT 1');const uid=`CP${String(Number(lastUser?.id||0)+1).padStart(8,'0')}`;const [result]=await pool.execute(`INSERT INTO users(uid,email,name,first_name,last_name,gender,date_of_birth,country,avatar_url,email_verified,kyc_status,status,balance,password,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,0,'not_submitted','pending',0,'',NOW(),NOW())`,[uid,email,profile.name||profile.full_name||email.split('@')[0],profile.first_name||profile.firstName||null,profile.last_name||profile.lastName||null,profile.gender||null,profile.dob||profile.date_of_birth||null,profile.country||null,profile.avatar_url||null]);const [newRows]=await pool.execute('SELECT * FROM users WHERE id=?',[result.insertId]);user=newRows[0];}const needsVerification=Number(user.email_verified||0)!==1||String(user.kyc_status||'not_submitted').toLowerCase()!=='approved'||String(user.status||'pending').toLowerCase()!=='active';return res.json({success:true,isNewUser,needsVerification,user:{id:user.id,uid:user.uid,email:user.email,name:user.name,first_name:user.first_name,last_name:user.last_name,email_verified:user.email_verified,kyc_status:user.kyc_status,status:user.status,gender:user.gender,date_of_birth:user.date_of_birth,country:user.country,avatar_url:user.avatar_url,balance:Number(user.balance||0)}});}catch(error){console.error('[sync-user] failed:',error.message);return res.status(500).json({success:false,message:'Unable to synchronize account'});}});
router.get('/verification-status',async(req,res)=>{try{const header=String(req.headers.authorization||'');if(!header.startsWith('Bearer '))return res.status(401).json({success:false,message:'Unauthorized'});const token=header.slice(7).trim();if(!token)return res.status(401).json({success:false,message:'Unauthorized'});const secret=process.env.JWT_SECRET;if(!secret)return res.status(500).json({success:false,message:'Authentication is not configured'});let decoded;try{decoded=jwt.verify(token,secret);}catch(_){return res.status(401).json({success:false,message:'Invalid or expired token'});}const email=safeEmail(decoded?.email);if(!email)return res.status(401).json({success:false,message:'Invalid authentication token'});const [rows]=await pool.execute('SELECT email_verified,kyc_status,status FROM users WHERE email=? LIMIT 1',[email]);if(!rows.length)return res.status(404).json({success:false,message:'User not found'});const u=rows[0],emailVerified=Number(u.email_verified||0)===1,kycStatus=u.kyc_status||'not_submitted',accountStatus=u.status||'pending';return res.json({success:true,status:{emailVerified,kycStatus,accountStatus,platformAccess:emailVerified&&kycStatus==='approved'&&accountStatus==='active'?'active':'locked'}});}catch(error){console.error('[verification-status] failed:',error.message);return res.status(500).json({success:false,message:'Unable to verify account status'});}});
router.post('/register',async(req,res)=>{try{res.json(await register(req.body));}catch(error){console.error('[register] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Registration failed'});}});
router.post('/login',async(req,res)=>{try{res.json(await login(req.body));}catch(error){console.error('[login] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Login failed'});}});
router.post('/verify-otp',async(req,res)=>{try{res.json(await verifyOtp(req.body));}catch(error){console.error('[verify-otp] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'OTP verification failed'});}});
router.post('/resend-otp',async(req,res)=>{try{res.json(await resendOtp(req.body));}catch(error){console.error('[resend-otp] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Unable to resend OTP'});}});
router.post('/verify-email-2fa',async(req,res)=>{try{res.json(await verifyEmail2fa(req.body));}catch(error){console.error('[verify-email-2fa] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Verification failed'});}});
router.post('/resend-email-2fa',async(req,res)=>{try{res.json(await resendEmail2fa(req.body));}catch(error){console.error('[resend-email-2fa] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Unable to resend verification'});}});
router.post('/verify-two-factor',async(req,res)=>{try{res.json(await verifyTwoFactor(req.body));}catch(error){console.error('[verify-two-factor] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Two-factor verification failed'});}});
router.post('/forgot-password',async(req,res)=>{try{res.json(await forgotPassword(req.body));}catch(error){console.error('[forgot-password] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Unable to process password reset'});}});
router.post('/reset-password',async(req,res)=>{try{res.json(await resetPassword(req.body));}catch(error){console.error('[reset-password] failed:',error.message);res.status(error.response?.status||500).json(error.response?.data||{success:false,message:'Unable to reset password'});}});
module.exports=router;
