// backend/src/routes/depositRoutes.js
const express = require('express');
const router = express.Router();
const multer = require('multer');
const crypto = require('crypto');
const pool = require('../../db');
const { authUser } = require('../middleware/auth');
const { createError } = require('../utils/helpers');
const storage = require('../../cloudinaryStorage');
const upload = multer({ storage });

const normalize = (value) => String(value || '').trim().toUpperCase();
const requestKey = (req) => String(req.get('Idempotency-Key') || req.body.idempotencyKey || '').trim().slice(0,128);
const makeReceiptHash = (coin,network,amount,txid,address) => crypto.createHash('sha256').update([coin,network,amount,txid,address].join('|')).digest('hex');

router.get('/deposit/wallets', authUser, async (req, res, next) => { try { const [rows] = await pool.execute(`SELECT id,coin,network,display_label AS label,address,minimum_deposit,minimum_deposit AS min_deposit,qr_image_url AS qr_url,qr_image_url,instructions FROM deposit_wallets WHERE status='active' ORDER BY sort_order ASC,id DESC`); res.json({success:true,data:rows}); } catch(error){next(error);} });
router.post('/deposits/upload-receipt',authUser,upload.single('receipt'),(req,res)=>{if(!req.file)return res.status(400).json({success:false,message:'No receipt uploaded'});res.json({success:true,data:{url:req.file.path},url:req.file.path});});

router.post('/deposits/request',authUser,async(req,res,next)=>{const connection=await pool.getConnection();try{const coin=normalize(req.body.coin),network=normalize(req.body.network),amount=Number(req.body.amount),txid=String(req.body.txid||'').trim(),note=String(req.body.note||'').trim(),proof=String(req.body.proof||'').trim(),address=String(req.body.address||'').trim(),key=requestKey(req);if(!coin||!network)throw createError(400,'Coin and network are required');if(!Number.isFinite(amount)||amount<=0)throw createError(400,'Invalid deposit amount');if(!key)throw createError(400,'Idempotency-Key is required');await connection.beginTransaction();const [wallets]=await connection.execute(`SELECT id,coin,network,address,minimum_deposit,status FROM deposit_wallets WHERE UPPER(coin)=? AND UPPER(network)=? AND status='active' FOR UPDATE`,[coin,network]);if(!wallets.length)throw createError(400,'Selected deposit wallet is not active');const wallet=wallets[0],minimum=Number(wallet.minimum_deposit||0);if(minimum>0&&amount<minimum)throw createError(400,`Minimum deposit is ${minimum} ${coin}`);if(address&&String(wallet.address).trim()!==address)throw createError(400,'Deposit address does not match the selected network wallet');const receiptHash=makeReceiptHash(coin,network,amount,txid,address);const [existing]=await connection.execute('SELECT id,coin,network,amount,status,txid,request_hash FROM deposits WHERE user_id=? AND idempotency_key=? LIMIT 1 FOR UPDATE',[req.user.id,key]);if(existing.length){if(existing[0].request_hash!==receiptHash){throw createError(409,'Idempotency-Key was already used for a different deposit request');}await connection.commit();return res.json({success:true,message:'Existing deposit request returned',data:{...existing[0],replayed:true}});}if(txid){const [duplicates]=await connection.execute(`SELECT id FROM deposits WHERE UPPER(coin)=? AND UPPER(network)=? AND txid=? AND status NOT IN ('rejected','cancelled') LIMIT 1 FOR UPDATE`,[coin,network,txid]);if(duplicates.length)throw createError(409,'This transaction reference has already been submitted');}const [same]=await connection.execute(`SELECT id FROM deposits WHERE user_id=? AND request_hash=? AND status NOT IN ('rejected','cancelled') LIMIT 1 FOR UPDATE`,[req.user.id,receiptHash]);if(same.length)throw createError(409,'An equivalent deposit request is already pending');const [result]=await connection.execute(`INSERT INTO deposits(user_id,coin,network,amount,txid,note,proof,status,idempotency_key,request_hash,created_at) VALUES(?,?,?,?,?,?,?,'pending',?,?,NOW())`,[req.user.id,coin,network,amount,txid||null,note||null,proof||null,key,receiptHash]);await connection.commit();res.json({success:true,message:'Deposit request submitted for verification',data:{id:result.insertId,status:'pending',coin,network,amount}});}catch(error){await connection.rollback();next(error)}finally{connection.release()}});
router.get('/deposits',authUser,async(req,res,next)=>{try{const [rows]=await pool.execute(`SELECT id,coin,network,amount,txid,note,proof,status,created_at,approved_at FROM deposits WHERE user_id=? ORDER BY id DESC`,[req.user.id]);res.json({success:true,data:rows});}catch(error){next(error);}});
module.exports=router;