// backend/src/routes/loanRoutes.js
const express = require('express');
const router = express.Router();
const pool = require('../../db');
const { authUser, authAdmin } = require('../middleware/auth');
const { createError, createTransactionLog, createUserNotification, createAuditLog } = require('../utils/helpers');
const { creditAssetBalance } = require('../../services/assetLedgerService');

router.post('/loans/apply', authUser, async (req,res,next)=>{try{
 const amount=Number(req.body.amount||0),durationCount=Number(req.body.durationCount||req.body.duration_count||1);
 const loanReason=String(req.body.reason||req.body.loan_reason||'').trim(),repaymentSource=String(req.body.repaymentSource||req.body.repayment_source||'').trim(),additionalNote=String(req.body.note||'').trim();
 const coin=String(req.body.coin||'USDT').trim().toUpperCase(),network=String(req.body.network||'INTERNAL').trim().toUpperCase();
 if(!Number.isFinite(amount)||amount<=0)throw createError(400,'Invalid loan amount');if(!Number.isFinite(durationCount)||durationCount<=0)throw createError(400,'Invalid duration');
 const [settingsRows]=await pool.execute('SELECT interest_rate, interest_type FROM loan_settings WHERE id=1');const settings=settingsRows[0]||{interest_rate:0,interest_type:'weekly'};const interestRate=Number(settings.interest_rate||0);const interestAmountPerPeriod=Number((amount*interestRate/100).toFixed(2));const totalInterest=Number((interestAmountPerPeriod*durationCount).toFixed(2));const totalRepayment=Number((amount+totalInterest).toFixed(2));
 const [result]=await pool.execute(`INSERT INTO loans (user_id,amount,interest_rate,interest_amount,interest_type,duration_count,loan_reason,repayment_source,note,total_repayment,status,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,'pending',NOW(),NOW())`,[req.user.id,amount,interestRate,totalInterest,settings.interest_type,durationCount,loanReason||null,repaymentSource||null,additionalNote||null,totalRepayment]);
 res.json({success:true,message:'Loan request submitted',data:{id:result.insertId,amount,coin,network,durationCount,interestRate,interestAmount:totalInterest,interestType:settings.interest_type,totalRepayment,status:'pending'}});
}catch(e){next(e)}});
router.get('/loans',authUser,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT * FROM loans WHERE user_id=? ORDER BY id DESC',[req.user.id]);res.json({success:true,data:rows})}catch(e){next(e)}});
router.get('/admin/loans',authAdmin,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT l.*,u.name,u.email FROM loans l LEFT JOIN users u ON u.id=l.user_id ORDER BY l.id DESC');res.json({success:true,data:rows})}catch(e){next(e)}});
router.post('/admin/loans/:id/approve',authAdmin,async(req,res,next)=>{const c=await pool.getConnection();try{const loanId=Number(req.params.id),coin=String(req.body.coin||'USDT').trim().toUpperCase(),network=String(req.body.network||'INTERNAL').trim().toUpperCase();if(!Number.isFinite(loanId))throw createError(400,'Invalid loan id');await c.beginTransaction();const [rows]=await c.execute('SELECT * FROM loans WHERE id=? FOR UPDATE',[loanId]);if(!rows.length)throw createError(404,'Loan not found');const loan=rows[0];if(loan.status!=='pending')throw createError(400,'Already processed');
 await creditAssetBalance(c,{userId:loan.user_id,coin,network,amount:Number(loan.amount),referenceType:'loan',referenceId:loan.id,note:`Loan #${loan.id} approved`});
 await c.execute("UPDATE loans SET status='approved',approved_at=NOW(),updated_at=NOW() WHERE id=?",[loanId]);await createTransactionLog(c,{userId:loan.user_id,type:'loan_credit',amount:loan.amount,status:'completed',referenceId:loan.id,note:`Loan #${loan.id} approved in ${coin}`});await createAuditLog(c,{adminId:req.admin.id,action:'approve_loan',targetUserId:loan.user_id,referenceId:loan.id,note:`Approved loan #${loan.id}: ${loan.amount} ${coin}/${network}`});await createUserNotification(c,{userId:loan.user_id,title:'Loan approved',message:`Your loan request for ${loan.amount} ${coin} has been approved.`,type:'general'});await c.commit();res.json({success:true,message:'Loan approved',data:{id:loan.id,coin,network,amount:Number(loan.amount)}})}catch(e){await c.rollback();next(e)}finally{c.release()}});
router.post('/admin/loans/:id/reject',authAdmin,async(req,res,next)=>{const c=await pool.getConnection();try{const loanId=Number(req.params.id);await c.beginTransaction();const [rows]=await c.execute('SELECT * FROM loans WHERE id=? FOR UPDATE',[loanId]);if(!rows.length)throw createError(404,'Loan not found');if(rows[0].status!=='pending')throw createError(400,'Already processed');await c.execute("UPDATE loans SET status='rejected',updated_at=NOW() WHERE id=?",[loanId]);await createAuditLog(c,{adminId:req.admin.id,action:'reject_loan',targetUserId:rows[0].user_id,referenceId:loanId,note:`Rejected loan #${loanId}`});await createUserNotification(c,{userId:rows[0].user_id,title:'Loan rejected',message:'Your loan request has been rejected.',type:'general'});await c.commit();res.json({success:true,message:'Loan rejected'})}catch(e){await c.rollback();next(e)}finally{c.release()}});
router.get('/admin/loan-settings',authAdmin,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT id,interest_rate,interest_type,created_at,updated_at FROM loan_settings WHERE id=1');res.json({success:true,data:rows[0]||{id:1,interest_rate:0,interest_type:'weekly'}})}catch(e){next(e)}});
async function updateSettings(req,res,next){try{const rate=Number(req.body.interest_rate||0),type=String(req.body.interest_type||'weekly').trim().toLowerCase();if(rate<0)throw createError(400,'Invalid interest rate');if(!['daily','weekly','monthly','yearly'].includes(type))throw createError(400,'Invalid interest type');await pool.execute('INSERT INTO loan_settings (id,interest_rate,interest_type,created_at,updated_at) VALUES (1,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE interest_rate=?,interest_type=?,updated_at=NOW()',[rate,type,rate,type]);await createAuditLog(pool,{adminId:req.admin.id,action:'update_loan_settings',referenceId:1,note:`Updated loan settings to ${rate}% ${type}`});res.json({success:true,message:'Loan settings updated'})}catch(e){next(e)}}
router.post('/admin/loan-settings',authAdmin,updateSettings);router.put('/admin/loan-settings',authAdmin,updateSettings);module.exports=router;