// backend/src/routes/tradeRoutes.js
const express = require('express');
const router = express.Router();
const pool = require('../../db');
const { authUser } = require('../middleware/auth');
const { createError, createTransactionLog } = require('../utils/helpers');
const { getBinancePrice, getTradeRuleByTimer } = require('../../services/tradeService');
const { moveAvailableToPending } = require('../../services/assetLedgerService');

router.get('/trade/rules', authUser, async (req, res, next) => { try { const [rows] = await pool.execute(`SELECT id,timer_seconds,payout_percent,status,created_at FROM trade_rules WHERE status='active' ORDER BY timer_seconds ASC`); res.json({success:true,data:rows}); } catch(e){next(e);} });
router.post('/trades/quick-amount', authUser, async(req,res,next)=>{try{const p=Number(req.body.percentage||0);if(![25,50,75].includes(p))throw createError(400,'Invalid percentage');const [rows]=await pool.execute(`SELECT available_balance FROM user_assets WHERE user_id=? AND coin='USDT'`,[req.user.id]);const b=Number(rows[0]?.available_balance||0);res.json({success:true,data:{amount:Number((b*p/100).toFixed(2)),percentage:p}})}catch(e){next(e)}});
router.post('/trades/place', authUser, async(req,res,next)=>{const db=await pool.getConnection();try{const pair=String(req.body.pair||'').trim().toUpperCase(),direction=String(req.body.direction||'').trim().toLowerCase(),timer=Number(req.body.timer||0),amount=Number(req.body.amount||0);if(!pair)throw createError(400,'Pair required');if(!['bullish','bearish'].includes(direction))throw createError(400,'Direction must be bullish or bearish');if(![60,180,300].includes(timer))throw createError(400,'Invalid timer');if(!Number.isFinite(amount)||amount<=0)throw createError(400,'Invalid trade amount');await db.beginTransaction();const [assetRows]=await db.execute(`SELECT available_balance FROM user_assets WHERE user_id=? AND coin='USDT' FOR UPDATE`,[req.user.id]);const available=Number(assetRows[0]?.available_balance||0);const rule=await getTradeRuleByTimer(db,timer);if(!rule)throw createError(400,'No active trade rule for this timer');if(available<amount)throw createError(400,'Insufficient USDT available balance');let entry=0;try{entry=await getBinancePrice(pair)}catch(_){}if(!Number.isFinite(Number(entry))||Number(entry)<=0)throw createError(503,'Live market price is unavailable. Trade was not opened.');const payout=Number(rule.payout_percent||0),end=new Date(Date.now()+timer*1000);const [result]=await db.execute(`INSERT INTO trades(user_id,pair,direction,timer_seconds,amount,entry_price,payout_percent,status,result,created_at,end_time) VALUES(?,?,?,?,?,?,?,'open',NULL,NOW(),?)`,[req.user.id,pair,direction,timer,amount,entry,payout,end]);await moveAvailableToPending(db,{userId:req.user.id,coin:'USDT',network:'INTERNAL',amount,entryType:'trade_stake_lock',referenceType:'trade',referenceId:result.insertId,note:`${pair} ${direction} trade stake locked`});await createTransactionLog(db,{userId:req.user.id,type:'trade_debit',amount,status:'completed',referenceId:result.insertId,note:`${pair} ${direction} trade opened`});await db.commit();res.json({success:true,message:'Trade placed',data:{tradeId:result.insertId,pair,direction,timer,amount,entryPrice:entry,payoutPercent:payout,endTime:end}})}catch(e){await db.rollback();next(e)}finally{db.release()}});
router.get('/trades/open',authUser,async(req,res,next)=>{try{const [r]=await pool.execute(`SELECT * FROM trades WHERE user_id=? AND status='open' ORDER BY id DESC`,[req.user.id]);res.json({success:true,data:r})}catch(e){next(e)}});
router.get('/trades/history',authUser,async(req,res,next)=>{try{const [r]=await pool.execute(`SELECT * FROM trades WHERE user_id=? ORDER BY id DESC LIMIT 200`,[req.user.id]);res.json({success:true,data:r})}catch(e){next(e)}});
module.exports=router;
