// backend/src/routes/userRoutes.js
const express = require('express');
const router = express.Router();
const multer = require('multer');
const bcrypt = require('bcryptjs');
const pool = require('../../db');
const { authUser } = require('../middleware/auth');
const storage = require('../../cloudinaryStorage');
const { createError, generateSixDigitOtp, isOtpExpired, createTransactionLog, createUserNotification, createAuditLog, removeUploadedFile, toNumber } = require('../utils/helpers');
const { sendOtpEmail } = require('../../services/emailService');
const { getBinanceHomeMarkets } = require('../../services/tradeService');
const upload = multer({ storage });

router.get('/user/profile', authUser, async (req,res,next)=>{try{const [rows]=await pool.execute(`SELECT id,uid,name,first_name,last_name,gender,date_of_birth,country,status,email_verified,kyc_status,approved_at,avatar_url,trading_fee_tier FROM users WHERE id=?`,[req.user.id]);if(!rows.length)throw createError(404,'User not found');res.json({success:true,data:rows[0]})}catch(e){next(e)}});
router.put('/user/profile',authUser,async(req,res,next)=>{try{const name=String(req.body.name||'').trim();if(!name)throw createError(400,'Name is required');await pool.execute('UPDATE users SET name=?,updated_at=NOW() WHERE id=?',[name,req.user.id]);const [rows]=await pool.execute('SELECT id,uid,name,first_name,last_name,gender,date_of_birth,country,status,email_verified,kyc_status,approved_at,avatar_url,trading_fee_tier FROM users WHERE id=?',[req.user.id]);res.json({success:true,message:'Profile updated',data:rows[0]})}catch(e){next(e)}});
router.post('/user/profile/upload-picture',authUser,upload.single('profile_picture'),async(req,res,next)=>{try{if(!req.file)throw createError(400,'Profile picture required');const [existing]=await pool.execute('SELECT avatar_url FROM users WHERE id=?',[req.user.id]);const oldAvatar=existing[0]?.avatar_url;const avatarUrl=req.file.path;await pool.execute('UPDATE users SET avatar_url=?,updated_at=NOW() WHERE id=?',[avatarUrl,req.user.id]);if(oldAvatar)removeUploadedFile(oldAvatar);res.json({success:true,message:'Profile picture updated',data:{avatar_url:avatarUrl}})}catch(e){next(e)}});
router.post('/user/set-passcode',authUser,async(req,res,next)=>{try{const passcode=String(req.body.passcode||'').trim();if(!/^\d{4,12}$/.test(passcode))throw createError(400,'Passcode must contain 4 to 12 digits');const hash=await bcrypt.hash(passcode,12);await pool.execute('UPDATE users SET passcode=?,updated_at=NOW() WHERE id=?',[hash,req.user.id]);res.json({success:true,message:'Transaction passcode saved'})}catch(e){next(e)}});
router.get('/user/security-status',authUser,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT passcode,twofa_enabled,email_verified,kyc_status,status,approved_at FROM users WHERE id=?',[req.user.id]);const u=rows[0]||{};res.json({success:true,data:{hasPasscode:!!u.passcode,passcode_enabled:!!u.passcode,twofaEnabled:!!u.twofa_enabled,email_verified:Number(u.email_verified||0),kyc_status:u.kyc_status||'not_submitted',status:u.status||'pending',approved_at:u.approved_at||null}})}catch(e){next(e)}});
router.post('/user/send-email-verification-code',authUser,async(req,res,next)=>{const c=await pool.getConnection();try{await c.beginTransaction();const [rows]=await c.execute('SELECT id,email FROM users WHERE id=? FOR UPDATE',[req.user.id]);if(!rows.length)throw createError(404,'User not found');const code=generateSixDigitOtp(),expiresAt=new Date(Date.now()+10*60*1000);await c.execute("UPDATE user_email_otps SET is_used=1,updated_at=NOW() WHERE user_id=? AND purpose='email_verification' AND is_used=0",[req.user.id]);await c.execute("INSERT INTO user_email_otps(user_id,email,otp_code,purpose,is_used,expires_at,created_at,updated_at) VALUES(?,?,?,'email_verification',0,?,NOW(),NOW())",[req.user.id,rows[0].email,code,expiresAt]);await c.commit();const emailSent=await sendOtpEmail({to:rows[0].email,code});res.json({success:true,message:'Verification code sent',emailSent:!!emailSent})}catch(e){await c.rollback();next(e)}finally{c.release()}});
router.post('/user/verify-email-code',authUser,async(req,res,next)=>{const c=await pool.getConnection();try{const code=String(req.body.code||'').trim();if(!/^\d{6}$/.test(code))throw createError(400,'Valid 6-digit code required');await c.beginTransaction();const [u]=await c.execute('SELECT id,email,kyc_status FROM users WHERE id=? FOR UPDATE',[req.user.id]);if(!u.length)throw createError(404,'User not found');const [o]=await c.execute("SELECT id,otp_code,expires_at FROM user_email_otps WHERE user_id=? AND email=? AND purpose='email_verification' AND is_used=0 ORDER BY id DESC LIMIT 1 FOR UPDATE",[req.user.id,u[0].email]);if(!o.length)throw createError(400,'No active verification code found');if(String(o[0].otp_code)!==code)throw createError(400,'Invalid verification code');if(isOtpExpired(o[0].expires_at))throw createError(400,'Verification code expired');await c.execute('UPDATE user_email_otps SET is_used=1,updated_at=NOW() WHERE id=?',[o[0].id]);await c.execute("UPDATE users SET email_verified=1,status=CASE WHEN kyc_status='pending' THEN 'under_review' ELSE status END,updated_at=NOW() WHERE id=?",[req.user.id]);await createUserNotification(c,{userId:req.user.id,title:'Email verified',message:'Your email address has been successfully verified.',type:'security'});await c.commit();res.json({success:true,message:'Email verified successfully'})}catch(e){await c.rollback();next(e)}finally{c.release()}});
router.get('/user/notifications',authUser,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT id,title,message,type,is_read,created_at FROM user_notifications WHERE user_id=? ORDER BY id DESC LIMIT 100',[req.user.id]);res.json({success:true,data:rows})}catch(e){next(e)}});
router.post('/user/notifications/:id/read',authUser,async(req,res,next)=>{try{await pool.execute('UPDATE user_notifications SET is_read=1 WHERE id=? AND user_id=?',[Number(req.params.id),req.user.id]);res.json({success:true,message:'Notification marked as read'})}catch(e){next(e)}});
router.delete('/user/notifications/:id',authUser,async(req,res,next)=>{try{const [r]=await pool.execute('DELETE FROM user_notifications WHERE id=? AND user_id=?',[Number(req.params.id),req.user.id]);if(!r.affectedRows)throw createError(404,'Notification not found');res.json({success:true,message:'Notification deleted'})}catch(e){next(e)}});
router.post('/user/verify-passcode',authUser,async(req,res,next)=>{try{const passcode=String(req.body.passcode||'').trim();const [rows]=await pool.execute('SELECT passcode FROM users WHERE id=?',[req.user.id]);if(!rows.length||!rows[0].passcode)throw createError(400,'No transaction passcode set');if(!await bcrypt.compare(passcode,String(rows[0].passcode)))throw createError(401,'Incorrect passcode');res.json({success:true,message:'Passcode verified'})}catch(e){next(e)}});
router.post('/kyc/upload',authUser,upload.fields([{name:'front',maxCount:1},{name:'back',maxCount:1}]),async(req,res,next)=>{try{const country=String(req.body.country||'').trim(),documentType=String(req.body.document_type||'').trim();if(!country)throw createError(400,'Country required');if(!documentType)throw createError(400,'Document type required');const frontFile=req.files?.front?.[0];if(!frontFile)throw createError(400,'Front document image required');const backUrl=req.files?.back?.[0]?.path||null;await pool.execute("UPDATE user_kyc SET verification_status='replaced' WHERE user_id=? AND verification_status='pending'",[req.user.id]);await pool.execute(`INSERT INTO user_kyc(user_id,residence_country,document_type,document_front_url,document_back_url,verification_status,submitted_at,created_at,updated_at) VALUES(?,?,?,?,?,'pending',NOW(),NOW(),NOW())`,[req.user.id,country,documentType,frontFile.path,backUrl]);const [u]=await pool.execute('SELECT email_verified FROM users WHERE id=?',[req.user.id]);await pool.execute("UPDATE users SET kyc_status='pending',status=?,country=COALESCE(NULLIF(?,''),country),updated_at=NOW() WHERE id=?",[Number(u[0]?.email_verified||0)===1?'under_review':'pending',country,req.user.id]);res.json({success:true,message:'KYC submitted successfully'})}catch(e){next(e)}});
router.get('/user/preferences',authUser,async(req,res,next)=>{try{const [rows]=await pool.execute('SELECT language,timezone,appearance,notifications_enabled,haptics_enabled,sounds_enabled FROM user_preferences WHERE user_id=?',[req.user.id]);const p=rows[0]||{language:'en',timezone:'UTC',appearance:'system',notifications_enabled:1,haptics_enabled:1,sounds_enabled:1};res.json({success:true,data:{language:p.language,timeZone:p.timezone,appearance:p.appearance,notifications:!!p.notifications_enabled,haptics:!!p.haptics_enabled,sounds:!!p.sounds_enabled}})}catch(e){next(e)}});
router.put('/user/preferences',authUser,async(req,res,next)=>{try{const body=req.body||{};const language=String(body.language||'en').slice(0,16);const timezone=String(body.timeZone||body.timezone||'UTC').slice(0,64);const appearance=['light','dark','system'].includes(body.appearance)?body.appearance:'system';const notifications=body.notifications===false?0:1;const haptics=body.haptics===false?0:1;const sounds=body.sounds===false?0:1;await pool.execute(`INSERT INTO user_preferences(user_id,language,timezone,appearance,notifications_enabled,haptics_enabled,sounds_enabled,created_at,updated_at) VALUES(?,?,?,?,?,?,?,NOW(),NOW()) ON DUPLICATE KEY UPDATE language=VALUES(language),timezone=VALUES(timezone),appearance=VALUES(appearance),notifications_enabled=VALUES(notifications_enabled),haptics_enabled=VALUES(haptics_enabled),sounds_enabled=VALUES(sounds_enabled),updated_at=NOW()`,[req.user.id,language,timezone,appearance,notifications,haptics,sounds]);res.json({success:true,message:'Preferences updated',data:{language,timeZone:timezone,appearance,notifications:!!notifications,haptics:!!haptics,sounds:!!sounds}})}catch(e){next(e)}});

module.exports=router;