import { useEffect,useMemo,useState } from "react";
import { Activity,Clock3,Wallet,ShieldCheck } from "lucide-react";
import { useNavigate,useParams } from "react-router-dom";
import MarketChart from "../../../components/MarketChart";
import OrderBook from "../../../components/OrderBook";
import { spotTradeApi,userApi,getApiErrorMessage } from "../../../services/api";
const ACTIVE="vexa_spot_long_term_active_position",RECEIPT="vexa_spot_long_term_receipt";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
const qty=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:8});
const listOf=v=>Array.isArray(v)?v:Array.isArray(v?.orders)?v.orders:Array.isArray(v?.data)?v.data:[];
const baseOf=s=>{const x=String(s||"").toUpperCase();return x.endsWith("USDT")?x.slice(0,-4):x};
export default function SpotPositionPage(){
 const navigate=useNavigate();const {symbol="BTCUSDT"}=useParams();const pair=String(symbol||"BTCUSDT").toUpperCase();const base=baseOf(pair);const auth=token();
 const [position,setPosition]=useState(null),[assets,setAssets]=useState([]),[orders,setOrders]=useState([]),[price,setPrice]=useState(0),[now,setNow]=useState(Date.now()),[error,setError]=useState(""),[syncing,setSyncing]=useState(false);
 useEffect(()=>{try{const x=JSON.parse(sessionStorage.getItem(ACTIVE)||"null");if(x)setPosition(x)}catch{}},[]);
 useEffect(()=>{const id=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(id)},[]);
 useEffect(()=>{let dead=false,ws;try{ws=new WebSocket(`wss://stream.binance.com:9443/ws/${pair.toLowerCase()}@ticker`);ws.onmessage=e=>{try{const p=Number(JSON.parse(e.data)?.c);if(!dead&&p>0)setPrice(p)}catch{}};ws.onerror=()=>{if(!dead)setError("Live market stream disconnected; waiting for a fresh quote.")}}catch{setError("Unable to connect to the live market stream.")}return()=>{dead=true;try{ws?.close()}catch{}}},[pair]);
 const load=async()=>{setSyncing(true);try{const [a,o]=await Promise.all([userApi.getUserAssets(auth),spotTradeApi.orders(auth)]);const ad=a.data?.data;setAssets(Array.isArray(ad?.assets)?ad.assets:Array.isArray(ad)?ad:[]);setOrders(listOf(o.data?.data))}catch(e){setError(getApiErrorMessage(e))}finally{setSyncing(false)}};
 useEffect(()=>{void load();const id=setInterval(()=>void load(),5000);return()=>clearInterval(id)},[auth]);
 const latest=useMemo(()=>position||orders.find(o=>String(o?.symbol||"").toUpperCase()===pair)||null,[position,orders,pair]);
 const side=String(latest?.side||"buy").toLowerCase(),entry=Number(latest?.executionPrice??latest?.execution_price??0),amount=Number(latest?.quantity||0);
 const livePnl=entry>0&&price>0?(side==="buy"?(price-entry)*amount:(entry-price)*amount):0,livePct=entry>0&&price>0?(side==="buy"?(price-entry)/entry:(entry-price)/entry)*100:0;
 const asset=assets.find(a=>String(a?.coin||a?.symbol||"").toUpperCase()===base),balance=Number(asset?.available_balance??asset?.availableBalance??asset?.balance??0),locked=Number(asset?.locked_balance??asset?.lockedBalance??asset?.locked??0);
 const orderId=latest?.orderId||latest?.id||latest?.order_id||"—",outcome=String(latest?.outcome||"").toLowerCase(),closed=side==="sell"&&Boolean(position);
 useEffect(()=>{if(!position||side!=="sell")return;sessionStorage.setItem(RECEIPT,JSON.stringify(position));sessionStorage.removeItem(ACTIVE);const t=setTimeout(()=>navigate("/trade/spot/long-term/result",{replace:true}),900);return()=>clearTimeout(t)},[position,side,navigate]);
 if(!latest)return <div className="fixed inset-0 z-[80] bg-[#030712] p-5 text-white">Preparing live Spot / Long-Term position…</div>;
 return <div className="fixed inset-0 z-[80] min-h-screen overflow-y-auto bg-[#030712] text-white">
  <header className="sticky top-0 z-20 border-b border-white/10 bg-[#050812]/95 px-4 py-3 backdrop-blur-xl sm:px-6 lg:px-8"><div className="flex items-center justify-between gap-4"><div><div className="flex items-center gap-2 text-[9px] font-bold uppercase tracking-[.3em] text-cyan-300"><Activity size={13}/>LIVE POSITION · SPOT / LONG-TERM</div><h1 className="mt-1 text-xl font-black sm:text-2xl">{pair}</h1><div className={side==="buy"?"text-[10px] font-bold text-emerald-300":"text-[10px] font-bold text-red-300"}>{side.toUpperCase()} · {closed?"POSITION CLOSING":"POSITION LIVE"}</div></div><div className="text-right"><div className="text-[9px] uppercase tracking-widest text-slate-500">LIVE MARKET</div><div className="text-3xl font-black tabular-nums text-cyan-300 sm:text-4xl">{price?money(price):"Streaming…"}</div><div className="text-[9px] text-slate-600">Market stream live · server sync {syncing?"pending":"active"}</div></div></div></header>
  <main className="grid w-full gap-3 p-3 sm:p-5 lg:grid-cols-[minmax(0,1.75fr)_minmax(340px,.65fr)] lg:p-7">
   <section className="min-w-0 space-y-3"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="text-[9px] text-slate-500">POSITION QTY</div><b className="mt-1 block text-sm">{qty(amount)} {base}</b></div><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="text-[9px] text-slate-500">ENTRY</div><b className="mt-1 block text-sm">{money(entry)}</b></div><div className="rounded-2xl border border-cyan-400/15 bg-cyan-400/5 p-3"><div className="text-[9px] text-cyan-300">LIVE VALUE</div><b className="mt-1 block text-sm">{price?money(price*amount)+" USDT":"—"}</b></div><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="text-[9px] text-slate-500">LIVE P/L</div><b className={livePnl>=0?"mt-1 block text-sm text-emerald-300":"mt-1 block text-sm text-red-300"}>{livePnl>=0?"+":""}{money(livePnl)} USDT <span className="text-[9px]">({livePct.toFixed(3)}%)</span></b></div></div><div className="overflow-hidden rounded-3xl border border-white/10 bg-[#0a0e1a] p-2 sm:p-3"><div className="mb-2 flex items-center justify-between px-1 text-[10px]"><span className="flex items-center gap-2 font-bold"><Activity size={14} className="text-cyan-300"/>LIVE MARKET CHART</span><span className="text-slate-600">{price?"LIVE TICK":"CONNECTING"}</span></div><MarketChart symbol={pair} interval="5m" height={430}/></div><OrderBook symbol={pair} currentPrice={price}/></section>
   <aside className="space-y-3"><section className="rounded-3xl border border-cyan-400/20 bg-[#0a0e1a] p-4"><div className="flex items-center gap-2 text-xs font-bold"><Wallet size={15} className="text-cyan-300"/>POSITION & BALANCE</div><div className="mt-3 grid grid-cols-2 gap-2 text-[10px]"><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Order ID</span><b className="mt-1 block">#{orderId}</b></div><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Side</span><b className="mt-1 block">{side.toUpperCase()}</b></div><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Available</span><b className="mt-1 block">{qty(balance)} {base}</b></div><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Locked</span><b className="mt-1 block">{qty(locked)} {base}</b></div><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Execution</span><b className="mt-1 block">{money(entry)}</b></div><div className="rounded-xl bg-[#050812] p-3"><span className="text-slate-600">Outcome</span><b className="mt-1 block">{outcome?outcome.toUpperCase():"OPEN"}</b></div></div></section><section className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex items-center gap-2 text-xs font-bold"><Clock3 size={15} className="text-cyan-300"/>LIVE PROCESSING</div><div className="mt-3 space-y-2 text-[10px]"><div className="flex justify-between"><span className="text-slate-600">Screen time</span><b>{new Date(now).toLocaleTimeString()}</b></div><div className="flex justify-between"><span className="text-slate-600">Market price</span><b className="text-cyan-300">{price?money(price):"—"}</b></div><div className="flex justify-between"><span className="text-slate-600">P/L movement</span><b className={livePnl>=0?"text-emerald-300":"text-red-300"}>{livePct>=0?"+":""}{livePct.toFixed(3)}%</b></div><div className="flex justify-between"><span className="text-slate-600">Position status</span><b className="text-amber-300">{closed?"CLOSING":"OPEN"}</b></div></div></section><div className="rounded-2xl border border-amber-400/10 bg-amber-400/5 p-3 text-[10px] leading-4 text-slate-500"><ShieldCheck size={13} className="mr-1 inline text-amber-300"/>Entire viewport live position. No X/close control, no Live View button and no client-side outcome forcing. Market value follows live ticks; realized P/L comes from the server order.</div>{error&&<div className="rounded-2xl border border-red-500/15 bg-red-500/10 p-3 text-[10px] text-red-300">{error}</div>}</aside>
  </main>
 </div>;
}
