import {useEffect,useRef,useState} from "react";
import {createChart,ColorType,CandlestickSeries} from "lightweight-charts";
import {marketApi} from "../services/api";
const SYMBOLS=["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT"];
const INTERVALS=["1m","5m","15m","1h","4h","1d"];
const fmt=v=>Number.isFinite(Number(v))?Number(v).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8}):"—";
export default function CryptoMarketPage(){
 const [symbol,setSymbol]=useState("BTCUSDT"),[interval,setIntervalValue]=useState("1m"),[ticker,setTicker]=useState(null),[connected,setConnected]=useState(false),[error,setError]=useState("");
 const containerRef=useRef(null),candleRef=useRef(null),socketRef=useRef(null),chartRef=useRef(null);
 useEffect(()=>{let live=true;const load=async()=>{try{const r=await marketApi.ticker(symbol);if(live)setTicker(r.data?.data||r.data||null)}catch{if(live)setError("Live market status is temporarily unavailable.")}};load();const id=setInterval(load,1000);return()=>{live=false;clearInterval(id)}},[symbol]);
 useEffect(()=>{const el=containerRef.current;if(!el)return;const chart=createChart(el,{autoSize:true,layout:{background:{type:ColorType.Solid,color:"#050812"},textColor:"#94a3b8"},grid:{vertLines:{color:"rgba(148,163,184,.06)"},horzLines:{color:"rgba(148,163,184,.06)"}},rightPriceScale:{borderColor:"rgba(148,163,184,.12)"},timeScale:{borderColor:"rgba(148,163,184,.12)",timeVisible:true,secondsVisible:interval==="1m"}});const series=chart.addSeries(CandlestickSeries,{upColor:"#10b981",downColor:"#ef4444",borderVisible:false,wickUpColor:"#10b981",wickDownColor:"#ef4444",lastValueVisible:true,priceLineVisible:true});chartRef.current=chart;candleRef.current=series;const ro=new ResizeObserver(()=>chart.resize(el.clientWidth,el.clientHeight));ro.observe(el);return()=>{ro.disconnect();chart.remove();chartRef.current=null;candleRef.current=null}},[interval]);
 useEffect(()=>{const series=candleRef.current;if(!series)return;let live=true;const load=async()=>{try{const r=await marketApi.klines(symbol,interval,300);const rows=r.data?.data||[];if(!live)return;series.setData(rows.map(k=>({time:Math.floor(Number(k[0])/1000),open:Number(k[1]),high:Number(k[2]),low:Number(k[3]),close:Number(k[4])})));chartRef.current?.timeScale().fitContent()}catch{if(live)setError("Unable to load candle history.")}};load();return()=>{live=false}},[symbol,interval]);
 useEffect(()=>{const series=candleRef.current;if(!series)return;const ws=new WebSocket("wss://stream.binance.com:9443/ws/"+symbol.toLowerCase()+"@kline_"+interval);socketRef.current=ws;setConnected(false);ws.onopen=()=>{setConnected(true);setError("")};ws.onmessage=e=>{try{const k=JSON.parse(e.data)?.k;if(!k)return;series.update({time:Math.floor(Number(k.t)/1000),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c)});setTicker(v=>({...v,symbol:symbol,price:Number(k.c),lastPrice:Number(k.c)}))}catch{}};ws.onerror=()=>setConnected(false);ws.onclose=()=>setConnected(false);return()=>{try{ws.close()}catch{}}},[symbol,interval]);
 const change=Number(ticker?.priceChangePercent||0),volume=Number(ticker?.volume||0);
 return <div className="min-h-screen bg-[#050812] px-3 pt-4 pb-24 text-white"><div className="mx-auto max-w-7xl space-y-4"><header className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-[9px] tracking-[.25em] text-cyan-300">VEXATRADE · CRYPTO MARKET</div><h1 className="mt-1 text-2xl font-bold">Live Crypto Market</h1><div className="mt-1 text-[10px] text-slate-500">Real exchange data · TradingView-style interactive chart</div></div><div className="flex items-center gap-2 text-[10px]"><span className={"h-2 w-2 rounded-full "+(connected?"bg-emerald-400":"bg-amber-400")}/>{connected?"LIVE STREAM":"RECONNECTING"}</div></div><div className="mt-4 flex flex-wrap gap-2">{SYMBOLS.map(x=><button key={x} onClick={()=>setSymbol(x)} className={"rounded-xl border px-4 py-2 text-xs font-bold "+(symbol===x?"border-cyan-300/30 bg-cyan-300/10 text-cyan-200":"border-white/10 text-slate-400")}>{x}</button>)}{INTERVALS.map(x=><button key={x} onClick={()=>setIntervalValue(x)} className={"rounded-xl px-3 py-2 text-[10px] "+(interval===x?"bg-white/10 text-white":"text-slate-500")}>{x}</button>)}</div></header><section className="rounded-3xl border border-white/10 bg-[#0a0e1a] overflow-hidden"><div className="grid grid-cols-2 border-b border-white/10 sm:grid-cols-4"><div className="p-4"><div className="text-[9px] text-slate-500">LAST PRICE</div><div className="mt-1 text-xl font-bold">{fmt(ticker?.price)}</div><div className="text-[9px] text-slate-500">USDT</div></div><div className="p-4"><div className="text-[9px] text-slate-500">24H CHANGE</div><div className={"mt-1 text-xl font-bold "+(change>=0?"text-emerald-300":"text-rose-300")}>{change>=0?"+":""}{change.toFixed(2)}%</div></div><div className="p-4"><div className="text-[9px] text-slate-500">24H HIGH / LOW</div><div className="mt-1 text-sm font-semibold">{fmt(ticker?.highPrice)} / {fmt(ticker?.lowPrice)}</div></div><div className="p-4"><div className="text-[9px] text-slate-500">24H VOLUME</div><div className="mt-1 text-sm font-semibold">{volume?volume.toLocaleString(undefined,{maximumFractionDigits:2}):"—"} {symbol.replace("USDT","")}</div></div></div><div ref={containerRef} className="h-[58vh] min-h-[420px] w-full"/>{error&&<div className="border-t border-amber-300/10 bg-amber-300/5 p-3 text-xs text-amber-200">{error}</div>}</section><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3 text-[10px] text-slate-500">Live candles are streamed from Binance WebSocket; VexaTrade backend supplies the historical candles and live 24-hour market status.</div></div></div>
}