import {useEffect,useState} from "react";
import {useNavigate} from "react-router-dom";
import {ArrowLeft,Clock3,RefreshCw,ShieldCheck,TrendingDown,TrendingUp} from "lucide-react";
import {digitalOptionsApi,userApi} from "../services/api";

const MATURITIES=[["30m","30 Minutes"],["1h","1 Hour"],["24h","24 Hours"],["30d","30 Days"],["1y","1 Year"]];
const PAIRS=["BTCUSDT","ETHUSDT"];

export default function DigitalOptionsPage(){
 const navigate=useNavigate(); const [settings,setSettings]=useState(null); const [active,setActive]=useState([]); const [pair,setPair]=useState("BTCUSDT"); const [timeframe,setTimeframe]=useState("30m"); const [stake,setStake]=useState(""); const [strike,setStrike]=useState(""); const [balance,setBalance]=useState(0); const [busy,setBusy]=useState(false); const [error,setError]=useState(""); const [notice,setNotice]=useState("");
 const token=localStorage.getItem("userToken")||localStorage.getItem("token")||"";
 const refresh=async()=>{try{const r=await Promise.all([digitalOptionsApi.settings(token),digitalOptionsApi.active(token),userApi.getWalletSummary(token)]);setSettings(r[0].data?.data||r[0].data);setActive(r[1].data?.data||[]);const d=r[2].data?.data||r[2].data||{};setBalance(Number(d?.assets?.USDT?.available_balance??d?.available_balance??0));}catch(e){setError(e?.response?.data?.message||"Unable to load Digital Options.");}};
 useEffect(()=>{refresh();const t=setInterval(refresh,5000);return()=>clearInterval(t)},[]);
 const place=async(direction)=>{setBusy(true);setError("");setNotice("");try{const r=await digitalOptionsApi.place({pair,direction,timeframeCode:timeframe,stake:Number(stake),strikePrice:Number(strike)||undefined},token);setNotice("Digital Option #"+r.data?.data?.id+" opened.");setStake("");await refresh()}catch(e){setError(e?.response?.data?.message||"Unable to open Digital Option.")}finally{setBusy(false)}};
 const cashout=async(id)=>{try{await digitalOptionsApi.cashout(id,token);setNotice("Position cashed out.");await refresh()}catch(e){setError(e?.response?.data?.message||"Cash-out unavailable.")}};
 return <div className="min-h-screen bg-[#050812] px-3 pt-4 pb-24 text-white"><div className="mx-auto max-w-5xl space-y-4">
 <button onClick={()=>navigate("/trade")} className="flex items-center gap-2 text-xs text-slate-400"><ArrowLeft size={15}/> Trade options</button>
 <header className="rounded-3xl border border-cyan-300/15 bg-cyan-300/5 p-5"><div className="text-[9px] font-bold tracking-[.28em] text-cyan-300">VEXATRADE · DIGITAL OPTIONS</div><h1 className="mt-2 text-2xl font-bold">Long-Horizon Digital Options</h1><p className="mt-1 text-xs leading-5 text-slate-400">Live barrier-based contracts with defined maturities and account-linked USDT settlement.</p><div className="mt-3 flex gap-2 text-[10px] text-emerald-300"><ShieldCheck size={14}/>Available USDT: {balance.toFixed(2)}</div></header>
 <section className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex items-center justify-between"><b>Choose maturity</b><button onClick={refresh} className="rounded-xl border border-white/10 p-2"><RefreshCw size={14}/></button></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5">{MATURITIES.map(([v,l])=><button key={v} onClick={()=>setTimeframe(v)} className="rounded-2xl border border-white/10 px-3 py-3 text-xs text-slate-300">{l}</button>)}</div>
 <div className="mt-4 grid gap-3 sm:grid-cols-2"><label className="text-xs text-slate-400">Market<select value={pair} onChange={e=>setPair(e.target.value)} className="mt-1 w-full rounded-xl border border-white/10 bg-[#050812] p-3 text-sm text-white">{PAIRS.map(p=><option key={p}>{p}</option>)}</select></label><label className="text-xs text-slate-400">Strike / barrier<input value={strike} onChange={e=>setStrike(e.target.value)} placeholder="Blank = current market price" inputMode="decimal" className="mt-1 w-full rounded-xl border border-white/10 bg-[#050812] p-3"/></label><label className="text-xs text-slate-400">Stake (USDT)<input value={stake} onChange={e=>setStake(e.target.value)} inputMode="decimal" className="mt-1 w-full rounded-xl border border-white/10 bg-[#050812] p-3"/></label><div className="rounded-xl border border-white/10 p-3 text-xs text-slate-400">Payout rate <b className="text-cyan-200">{Number(settings?.payout_rate??88)}%</b></div></div>
 <div className="mt-4 grid grid-cols-2 gap-3"><button disabled={busy} onClick={()=>place("CALL")} className="rounded-2xl bg-emerald-500/15 p-4 font-bold text-emerald-300"><TrendingUp className="mx-auto mb-1" size={18}/>CALL</button><button disabled={busy} onClick={()=>place("PUT")} className="rounded-2xl bg-rose-500/15 p-4 font-bold text-rose-300"><TrendingDown className="mx-auto mb-1" size={18}/>PUT</button></div></section>
 {(notice||error)&&<div className="rounded-2xl border border-white/10 p-3 text-xs">{error||notice}</div>}
 <section className="rounded-3xl border border-white/10 bg-[#0a0e1a] p-4"><div className="mb-3 flex items-center gap-2"><Clock3 size={15} className="text-cyan-300"/><b>Running positions</b></div>{active.length?active.map(t=><Position key={t.id} trade={t} onCashout={cashout}/>):<div className="py-8 text-center text-xs text-slate-500">No active Digital Options.</div>}</section></div></div>;
}
function Position({trade,onCashout}){const [now,setNow]=useState(Date.now());useEffect(()=>{const x=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(x)},[]);const seconds=Math.max(0,Math.floor((new Date(trade.expiration_time).getTime()-now)/1000));return <div className="rounded-2xl border border-white/10 p-4"><div className="flex justify-between"><b>{trade.asset_pair} · {trade.direction}</b><span className="text-cyan-300">{seconds}s</span></div><div className="mt-2 grid grid-cols-2 gap-2 text-[10px] text-slate-400"><span>Entry {Number(trade.entry_spot_price).toFixed(4)}</span><span>Barrier {Number(trade.strike_price).toFixed(4)}</span><span>Live {trade.live_price?Number(trade.live_price).toFixed(4):"—"}</span><span>Probability {trade.probability==null?"—":(Number(trade.probability)*100).toFixed(1)+"%"}</span></div><button disabled={!trade.cashout_value||seconds<=0} onClick={()=>onCashout(trade.id)} className="mt-3 w-full rounded-xl border border-cyan-300/20 p-3 text-xs font-bold text-cyan-200">Cash out {trade.cashout_value?Number(trade.cashout_value).toFixed(2)+" USDT":""}</button></div>}
