import { useEffect,useMemo,useState } from "react";
import { CheckCircle2,Copy,FileUp,RefreshCw,ShieldCheck } from "lucide-react";
import { getAccountVerification,submitAccountVerification } from "../services/api";
export default function ExternalWalletVerificationPage(){
 const token=localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
 const [data,setData]=useState(null),[loading,setLoading]=useState(true),[submitting,setSubmitting]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(false),[tx,setTx]=useState(""),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[file,setFile]=useState(null);
 async function load(){try{setLoading(true);setError("");const r=await getAccountVerification(token);setData(r?.data?.data||r?.data||null)}catch(e){setError(e?.response?.data?.message||e?.message||"Unable to load verification status.")}finally{setLoading(false)}}
 useEffect(()=>{void load();const id=setInterval(()=>void load(),10000);return()=>clearInterval(id)},[]);
 const step=useMemo(()=>data?.steps?.find(s=>Number(s.stepNumber||s.step_number)===Number(data?.currentStep||0))||null,[data]);
 const requiredAmount=step?.requiredAmountDisplay||step?.required_amount_display||step?.requiredAmount||step?.required_amount;
 const address=step?.verificationAddress||step?.verification_address||"";
 async function copy(){try{await navigator.clipboard.writeText(address);setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}}
 async function submit(e){e.preventDefault();if(!step)return;try{setSubmitting(true);setError("");const fd=new FormData();fd.append("transaction_hash",tx.trim());fd.append("amount",amount.trim());fd.append("evidence_note",note.trim());if(file)fd.append("receipt",file);await submitAccountVerification(Number(data.currentStep),fd,token);setTx("");setAmount("");setNote("");setFile(null);await load()}catch(e){setError(e?.response?.data?.message||e?.message||"Submission failed.")}finally{setSubmitting(false)}}
 if(loading)return <div className="min-h-screen bg-[#050812] p-5 text-sm text-slate-300">Loading verification…</div>;
 if(!data?.enabled)return <div className="min-h-screen bg-[#050812] p-5 text-sm text-slate-300">No active external wallet verification is required.</div>;
 return <div className="min-h-screen bg-[#050812] px-4 py-6 text-white"><div className="mx-auto max-w-md space-y-4">
 <section className="rounded-[28px] border border-cyan-400/15 bg-[#0a0e1a] p-5 shadow-2xl"><div className="flex items-center gap-3"><div className="rounded-2xl bg-cyan-500/10 p-3"><ShieldCheck className="text-cyan-300" size={22}/></div><div><div className="text-[10px] uppercase tracking-[.28em] text-cyan-300">Account access</div><h1 className="mt-1 text-xl font-bold">{data.title||"External Wallet Verification"}</h1></div></div><p className="mt-4 text-xs leading-5 text-slate-400">{data.description||"Complete each verification stage in order while your evidence is reviewed."}</p><div className="mt-5 grid grid-cols-3 gap-2">{[1,2,3].map(n=>{const s=data.steps?.find(x=>Number(x.stepNumber||x.step_number)===n),st=s?.status||"locked";return <div key={n} className={"rounded-xl border p-2 text-center "+(st==="completed"?"border-emerald-500/20 bg-emerald-500/10":"border-white/10 bg-white/[.02]")}><div className="text-[10px] text-slate-500">Stage {n}</div><div className="mt-1 text-[10px] font-semibold capitalize text-slate-200">{st.replaceAll("_"," ")}</div></div>})}</div></section>
 {error?<div className="rounded-xl border border-red-500/20 bg-red-500/10 px-3 py-3 text-xs text-red-300">{error}</div>:null}
 {step?<><section className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-4 shadow-xl"><div className="flex items-start justify-between gap-3"><div><div className="text-[10px] uppercase tracking-[.22em] text-cyan-300">Current stage {data.currentStep}</div><h2 className="mt-1 text-lg font-semibold">{step.title||("Verification Step "+data.currentStep)}</h2></div><span className="rounded-full border border-cyan-400/15 bg-cyan-500/10 px-2 py-1 text-[10px] text-cyan-300">{step.coin} · {step.network}</span></div><p className="mt-3 text-xs leading-5 text-slate-400">{step.description||"Follow the configured verification instructions and submit your evidence."}</p><div className="mt-4 rounded-2xl border border-white/10 bg-[#050812] p-3"><div className="text-[10px] uppercase tracking-wider text-slate-500">Verification address</div><div className="mt-2 break-all text-xs font-mono text-slate-200">{address}</div><button onClick={copy} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-white/10 px-3 py-2 text-[11px] text-white"><Copy size={13}/>{copied?"Copied":"Copy address"}</button></div>{requiredAmount?<div className="mt-3 rounded-2xl border border-amber-400/15 bg-amber-500/5 p-3"><div className="text-[10px] uppercase tracking-wider text-amber-300">Required exact amount</div><div className="mt-1 text-xl font-bold text-white">{requiredAmount}</div><div className="mt-1 text-[10px] text-slate-500">This amount is stored as a verification requirement only; this workflow does not debit or credit the VexaTrade financial ledger.</div></div>:null}</section>
 <form onSubmit={submit} className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-4 shadow-xl space-y-3"><input value={amount} onChange={e=>setAmount(e.target.value)} placeholder={requiredAmount?"Enter exact required amount":"Amount"} inputMode="decimal" required={Boolean(requiredAmount)} className="w-full rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><input value={tx} onChange={e=>setTx(e.target.value)} placeholder="Transaction hash / reference" required={step.transactionHashRequired!==false&&step.transaction_hash_required!==0} className="w-full rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><label className="flex items-center gap-2 rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-xs text-slate-400"><FileUp size={15}/><span className="flex-1 truncate">{file?.name||"Upload receipt / evidence"}</span><span className="rounded-lg bg-white/[.06] px-2 py-1 text-white">Choose</span><input type="file" accept="image/*,.pdf" onChange={e=>setFile(e.target.files?.[0]||null)} className="hidden"/></label><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Evidence note (optional)" className="w-full rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm text-white"/><button disabled={submitting} className="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-cyan-500 px-4 py-3 text-sm font-bold text-slate-950">{submitting?<RefreshCw size={15} className="animate-spin"/>:<CheckCircle2 size={15}/>} {submitting?"Submitting…":"Submit verification evidence"}</button></form></>:<section className="rounded-[24px] border border-white/10 bg-[#0a0e1a] p-6 text-center text-sm text-slate-400">Your current stage is processing. Refresh for the next stage or approval result.</section>}
 <button onClick={()=>void load()} className="mx-auto flex items-center gap-2 text-xs text-slate-500"><RefreshCw size={13}/>Refresh status</button></div></div>
}