import { useEffect,useState } from "react";
import { useNavigate,useParams } from "react-router-dom";
import { CheckCircle2, Loader2, Lock, ShieldCheck } from "lucide-react";
import { fundsApi } from "../services/api";
import { createActionIdempotencyKey,runSingleUserAction } from "../services/actionRequest";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:6});
export default function FundApplyPage(){const {planId}=useParams();const nav=useNavigate();const [plan,setPlan]=useState(null);const [amount,setAmount]=useState("");const [loading,setLoading]=useState(true);const [processing,setProcessing]=useState(false);const [result,setResult]=useState(null);const [error,setError]=useState("");
useEffect(()=>{fundsApi.plans(token()).then(r=>{const rows=Array.isArray(r?.data?.data)?r.data.data:[];setPlan(rows.find(x=>String(x.id)===String(planId))||null)}).catch(e=>setError(e?.message||"Unable to load plan")).finally(()=>setLoading(false))},[planId]);
async function submit(){const value=Number(amount);if(!plan||!Number.isFinite(value)||value<=0)return setError("Enter a valid amount.");if(value<Number(plan.min_amount||0))return setError("Amount is below the plan minimum.");if(plan.max_amount!=null&&value>Number(plan.max_amount))return setError("Amount exceeds the plan maximum.");try{setProcessing(true);setError("");const key=createActionIdempotencyKey("funds-apply");const r=await runSingleUserAction("funds-submit",()=>fundsApi.apply({plan_id:plan.id,amount:value,idempotencyKey:key},token()));setResult(r?.data?.data||{});}catch(e){setError(e?.response?.data?.message||e?.message||"Fund application failed.");}finally{setProcessing(false)}}
if(loading)return <div className="min-h-screen bg-[#050812] p-4 text-xs text-slate-400">Loading…</div>;
if(result)return <div className="min-h-screen bg-[#050812] p-3 pb-24 sm:p-5"><div className="mx-auto max-w-md rounded-2xl border border-emerald-400/20 bg-[#0a0e1a] p-5 text-center"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-emerald-400/10"><CheckCircle2 className="text-emerald-300"/></div><h1 className="mt-3 text-lg font-bold text-white">Trust Fund is active</h1><p className="mt-1 text-[10px] text-slate-500">Your Vexa Blockchain Ecosystem-confirmed fund is now visible in Live Active Trust Funds.</p><div className="mt-4 rounded-xl border border-white/10 bg-[#050812] p-3 text-left text-[10px]"><div>Fund ID: <b className="text-white">#{result.fund_id}</b></div><div className="mt-1">Amount: <b className="text-white">{money(result.amount)} USDT</b></div><div className="mt-1">Daily rate: <b className="text-emerald-300">{result.selected_daily_profit_percent}%</b></div></div><button onClick={()=>nav("/funds/active")} className="mt-4 w-full rounded-xl bg-cyan-500 py-2.5 text-xs font-bold text-black">Open Live Active Fund</button></div></div>;
if(!plan)return <div className="min-h-screen bg-[#050812] p-4 text-xs text-slate-400">{error||"Plan unavailable."}</div>;
return <div className="min-h-screen bg-[#050812] p-3 pb-24 sm:p-5"><div className="mx-auto max-w-md rounded-2xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex items-start justify-between"><div><div className="text-[9px] uppercase tracking-wider text-cyan-300">Secure application</div><h1 className="mt-1 text-lg font-bold text-white">{plan.name}</h1><div className="text-[10px] text-slate-500">{plan.duration_days} days · {plan.is_private?"Private":"Public"}</div></div><Lock size={17} className={plan.is_private?"text-amber-400":"text-emerald-400"}/></div><div className="mt-4 rounded-xl border border-white/10 bg-[#050812] p-3"><div className="text-[9px] text-slate-500">Funding amount</div><input value={amount} onChange={e=>setAmount(e.target.value)} type="number" min={plan.min_amount||0} step="0.01" placeholder={String(plan.min_amount||0)} className="mt-1 w-full bg-transparent text-xl font-bold text-white outline-none"/><div className="mt-2 text-[9px] text-slate-500">Range: {money(plan.min_amount)} – {plan.max_amount==null?"Unlimited":money(plan.max_amount)} USDT</div></div>{error&&<div className="mt-2 rounded-lg bg-red-400/10 p-2 text-[10px] text-red-300">{error}</div>}<div className="mt-3 flex items-center gap-2 text-[9px] text-slate-500"><ShieldCheck size={12} className="text-emerald-400"/> Vexa Blockchain Ecosystem validation covers balance, authorization, limits and transaction identity.</div><button onClick={submit} disabled={processing} className="mt-4 w-full rounded-xl bg-cyan-500 py-2.5 text-xs font-bold text-black disabled:opacity-60">{processing?<><Loader2 size={13} className="mr-1 inline animate-spin"/>Processing securely…</>:"Confirm funding"}</button></div></div>}