import { useEffect,useState } from "react";
import { useParams,useNavigate } from "react-router-dom";
import { ArrowLeft, CheckCircle2, Lock, ShieldCheck } from "lucide-react";
import { fundsApi } from "../services/api";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
export default function FundsPlanDetailsPage(){const {planId}=useParams();const nav=useNavigate();const [plan,setPlan]=useState(null);const [loading,setLoading]=useState(true);const [error,setError]=useState("");
 useEffect(()=>{let ok=true;fundsApi.plans(token()).then(r=>{const rows=Array.isArray(r?.data?.data)?r.data.data:[];const p=rows.find(x=>String(x.id)===String(planId));if(ok)setPlan(p||null)}).catch(e=>ok&&setError(e?.message||"Unable to load plan")).finally(()=>ok&&setLoading(false));return()=>{ok=false}},[planId]);
 if(loading)return <div className="min-h-screen bg-[#050812] p-4 text-xs text-slate-400">Loading plan…</div>;
 if(!plan)return <div className="min-h-screen bg-[#050812] p-4"><button onClick={()=>nav("/funds")} className="text-xs text-cyan-300">← Back to Trust Funds</button><div className="mt-4 rounded-xl border border-white/10 bg-[#0a0e1a] p-5 text-xs text-slate-400">{error||"Plan is unavailable or not assigned to this account."}</div></div>;
 return <div className="min-h-screen bg-[#050812] p-3 pb-24 sm:p-5"><div className="mx-auto max-w-3xl"><button onClick={()=>nav(-1)} className="mb-3 inline-flex items-center gap-1 text-xs text-slate-400"><ArrowLeft size={13}/> Back</button><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-4 shadow-xl"><div className="flex items-start justify-between gap-3"><div><div className="text-[9px] uppercase tracking-wider text-cyan-300">VexaTrade Trust Fund Plan</div><h1 className="mt-1 text-xl font-bold text-white">{plan.name}</h1><div className="mt-1 text-xs text-slate-400">{plan.duration_days} days · {plan.is_private?"Private assignment":"Public plan"}</div></div>{plan.is_private?<Lock className="text-amber-400" size={18}/>:<ShieldCheck className="text-emerald-400" size={18}/>}</div><div className="mt-4 grid grid-cols-2 gap-2 sm:grid-cols-4">{[["Minimum",money(plan.min_amount)+" USDT"],["Maximum",plan.max_amount==null?"Unlimited":money(plan.max_amount)+" USDT"],["Daily",Number(plan.min_daily_profit_percent).toFixed(2)+"–"+Number(plan.max_daily_profit_percent).toFixed(2)+"%"],["Usage",plan.user_limit_count==null?"Unlimited":plan.user_limit_count+" times"]].map(([a,b])=><div key={a} className="rounded-xl border border-white/10 bg-[#050812] p-2"><div className="text-[9px] text-slate-500">{a}</div><div className="mt-1 text-xs font-semibold text-white">{b}</div></div>)}</div><div className="mt-4 space-y-2 text-xs text-slate-300">{plan.admin_note&&<p className="whitespace-pre-wrap">{plan.admin_note}</p>}{plan.additional_notes&&<p className="whitespace-pre-wrap text-slate-400">{plan.additional_notes}</p>}{plan.disclaimer&&<p className="rounded-lg border border-amber-400/20 bg-amber-400/5 p-2 text-amber-300">{plan.disclaimer}</p>}</div><button onClick={()=>nav("/funds/apply/"+encodeURIComponent(plan.id))} className="mt-4 w-full rounded-xl bg-cyan-500 py-2.5 text-xs font-bold text-black"><CheckCircle2 size={13} className="mr-1 inline"/> Continue to application</button></div></div></div>
}