import { useEffect,useState } from "react";
import { ArrowLeft,CheckCircle2,Copy,History,Wallet } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { spotTradeApi } from "../services/api";
const KEY="vexa_spot_long_term_receipt",token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
export default function SpotTradingResultPage(){
 const navigate=useNavigate(),[receipt,setReceipt]=useState(null),[copied,setCopied]=useState(false),[orders,setOrders]=useState([]);
 const refresh=()=>spotTradeApi.orders(token()).then(r=>setOrders(Array.isArray(r.data?.data)?r.data.data:[])).catch(()=>{});
 useEffect(()=>{try{const r=JSON.parse(sessionStorage.getItem(KEY)||"null");if(!r){navigate("/trade/spot",{replace:true});return}setReceipt(r)}catch{navigate("/trade/spot",{replace:true})};refresh()},[navigate]);
 if(!receipt)return <div className="min-h-screen bg-[#050812] p-4 text-white">Loading receipt...</div>;
 const id=receipt.orderId||receipt.id||"—";
 const copy=async()=>{try{await navigator.clipboard.writeText(String(id));setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}};
 return <div className="min-h-screen bg-[#050812] p-3 pb-24 text-white sm:p-4"><div className="mx-auto max-w-3xl space-y-3"><section className="rounded-3xl border border-emerald-400/20 bg-[#0a0e1a] p-5 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={48}/><div className="mt-2 text-[10px] uppercase tracking-[0.3em] text-emerald-300">Step 3 · Completed</div><h1 className="mt-1 text-2xl font-bold">Spot Order Filled</h1><p className="mt-1 text-xs text-slate-500">Your confirmed market order has been settled into the VexaTrade asset ledger.</p></section><section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-4"><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-slate-500">Pair</span><b className="mt-1 block">{receipt.symbol}</b></div><div><span className="text-slate-500">Side</span><b className="mt-1 block">{String(receipt.side).toUpperCase()}</b></div><div><span className="text-slate-500">Quantity</span><b className="mt-1 block">{receipt.quantity}</b></div><div><span className="text-slate-500">Execution price</span><b className="mt-1 block">{money(receipt.executionPrice)}</b></div><div><span className="text-slate-500">Quote amount</span><b className="mt-1 block">{money(receipt.quoteAmount)} USDT</b></div><div><span className="text-slate-500">Status</span><b className="mt-1 block text-emerald-300">{receipt.status||"filled"}</b></div></div><div className="mt-4 flex items-center justify-between rounded-xl bg-[#050812] p-3 text-xs"><span className="text-slate-500">Order ID</span><button onClick={copy} className="flex items-center gap-2 font-semibold">{copied?"Copied":"#"+id}<Copy size={13}/></button></div></section><div className="grid grid-cols-2 gap-2"><button onClick={()=>{sessionStorage.removeItem(KEY);navigate("/trade/spot")}} className="rounded-xl bg-cyan-400 py-3 text-sm font-bold text-black"><Wallet className="mr-1 inline" size={15}/>New Order</button><button onClick={()=>navigate("/trade/spot")} className="rounded-xl border border-white/10 py-3 text-sm"><History className="mr-1 inline" size={15}/>Trade Again</button></div><section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Recent spot orders</h2><button onClick={refresh} className="text-[10px] text-cyan-300">Refresh</button></div><div className="mt-3 space-y-2">{orders.slice(0,10).map((o,i)=><div key={o.id||i} className="flex justify-between rounded-xl bg-[#050812] p-3 text-[10px]"><span>{o.symbol} · {String(o.side).toUpperCase()}</span><span>{money(o.execution_price||o.executionPrice)}</span><span className="text-emerald-300">{o.status||"filled"}</span></div>)}</div></section><button onClick={()=>navigate("/trade")} className="flex w-full items-center justify-center gap-1 py-2 text-[10px] text-slate-500"><ArrowLeft size={12}/>Back to Trade</button></div></div>;
}