import { useEffect,useState } from "react";
import { ArrowLeft,ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import MarketChart from "../components/MarketChart";
import OrderBook from "../components/OrderBook";
import { spotTradeApi,getApiErrorMessage } from "../services/api";
import { createActionIdempotencyKey,runSingleUserAction } from "../services/actionRequest";
import { useNotification } from "../hooks/useNotification";
const DRAFT="vexa_spot_long_term_draft",RECEIPT="vexa_spot_long_term_receipt",token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
export default function SpotTradingReviewPage(){
 const navigate=useNavigate(),auth=token(),{showError}=useNotification();const[draft,setDraft]=useState(null),[price,setPrice]=useState(0),[quoteAt,setQuoteAt]=useState(0),[settings,setSettings]=useState(null),[processing,setProcessing]=useState(false),[error,setError]=useState("");
 useEffect(()=>{try{const d=JSON.parse(sessionStorage.getItem(DRAFT)||"null");if(!d)navigate("/trade/spot",{replace:true});else setDraft(d)}catch{navigate("/trade/spot",{replace:true})}},[navigate]);
 useEffect(()=>{if(!draft)return;let closed=false;const ws=new WebSocket("wss://stream.binance.com:9443/ws/"+draft.pair.toLowerCase()+"@ticker");ws.onmessage=e=>{try{const p=Number(JSON.parse(e.data)?.c);if(!closed&&p>0){setPrice(p);setQuoteAt(Date.now())}}catch{}};return()=>{closed=true;try{ws.close()}catch{}}},[draft]);
 useEffect(()=>{spotTradeApi.settings(auth).then(r=>setSettings(r.data?.data||null)).catch(()=>{})},[auth]);
 if(!draft)return <div className="min-h-screen bg-[#050812] p-4 text-white">Preparing review...</div>;
 const age=quoteAt?Math.floor((Date.now()-quoteAt)/1000):null,observed=Number(draft.observedPrice),qty=Number(draft.quantity),total=qty*observed,maxSlippage=Number(settings?.maxSlippageBps||100),min=Number(settings?.minOrderUsdt||10),max=Number(settings?.maxOrderUsdt||100000);
 async function confirm(){if(processing)return;if(!price||age===null||age>15)return setError("Live market price is unavailable or stale. Refresh the review before confirming.");if(total<min||total>max)return setError("The order is outside the current server-configured limits.");const key=createActionIdempotencyKey("spot-order");setProcessing(true);setError("");try{const r=await runSingleUserAction("spot-market-order",()=>spotTradeApi.placeMarket({symbol:draft.pair,side:draft.side,quantity:qty,price:observed,idempotencyKey:key},auth));const data=r.data?.data;if(!data)throw new Error(r.data?.message||"Spot order was not completed");sessionStorage.setItem(RECEIPT,JSON.stringify(data));sessionStorage.removeItem(DRAFT);navigate("/trade/spot/result",{replace:true})}catch(e){const m=getApiErrorMessage(e);setError(m);showError?.(m)}finally{setProcessing(false)}}
 return <div className="min-h-screen bg-[#050812] p-3 pb-24 text-white sm:p-4"><div className="mx-auto max-w-6xl space-y-3"><header className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><button onClick={()=>navigate("/trade/spot")} className="flex items-center gap-1 text-[10px] text-slate-500"><ArrowLeft size={12}/>Edit order</button><div className="mt-2 text-[10px] uppercase tracking-[0.28em] text-cyan-300">Step 2 · Confirm</div><h1 className="mt-1 text-lg font-bold">{draft.side==="buy"?"Buy":"Sell"} {draft.pair}</h1><div className="mt-2 grid grid-cols-3 gap-1.5 text-center text-[9px] uppercase tracking-wider"><div className="rounded-xl bg-[#050812] p-2 text-slate-600">1 · Configure</div><div className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-2 text-cyan-300">2 · Review & Confirm</div><div className="rounded-xl bg-[#050812] p-2 text-slate-600">3 · Result</div></div></header>
 <section className="grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-3"><section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex justify-between"><div><div className="text-[9px] text-slate-500">Live market chart</div><div className="text-xs">{draft.pair}</div></div><div className="text-right"><div className="text-[9px] text-slate-500">Current price</div><b>{price?money(price):"Connecting..."}</b></div></div><MarketChart symbol={draft.pair} interval="5m" height={260}/></section><OrderBook symbol={draft.pair} currentPrice={price}/></div>
 <section className="rounded-2xl border border-cyan-400/20 bg-[#0a0e1a] p-4"><div className="flex items-center gap-2 text-sm font-bold"><ShieldCheck size={17} className="text-cyan-300"/>Final confirmation</div><div className="mt-3 space-y-2 rounded-2xl bg-[#050812] p-3 text-xs"><div className="flex justify-between"><span className="text-slate-500">Pair</span><b>{draft.pair}</b></div><div className="flex justify-between"><span className="text-slate-500">Side</span><b className={draft.side==="buy"?"text-emerald-300":"text-red-300"}>{draft.side.toUpperCase()}</b></div><div className="flex justify-between"><span className="text-slate-500">Quantity</span><b>{draft.quantity}</b></div><div className="flex justify-between"><span className="text-slate-500">Review price</span><b>{money(observed)}</b></div><div className="flex justify-between"><span className="text-slate-500">Current price</span><b>{price?money(price):"—"}</b></div><div className="flex justify-between font-bold"><span>Estimated total</span><b>{money(total)} USDT</b></div><div className="flex justify-between text-[10px]"><span className="text-slate-500">Quote age</span><span>{age===null?"Waiting":age+"s"}</span></div><div className="flex justify-between text-[10px]"><span className="text-slate-500">Allowed movement</span><span>{maxSlippage} bps</span></div></div><div className="mt-3 rounded-xl border border-amber-400/10 bg-amber-400/5 p-3 text-[10px] leading-4 text-slate-500">The server re-checks live execution price, limits, balance, idempotency and transaction security. The final fill can differ from the review quote within the configured limit.</div>{error&&<div className="mt-3 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-[11px] text-red-300">{error}</div>}<button onClick={confirm} disabled={processing||!price||age===null||age>15} className="mt-4 w-full rounded-2xl bg-emerald-400 py-3 text-sm font-bold text-black disabled:opacity-40">{processing?"Processing one order...":"Confirm & Execute"}</button><button onClick={()=>navigate("/trade/spot")} disabled={processing} className="mt-2 w-full rounded-xl border border-white/10 py-2.5 text-xs text-slate-300">Back to Configure</button></section></section></div></div>;
}