import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,RefreshCw,Wallet,BarChart3,ShieldCheck,History,ChevronRight,Activity,Info,CheckCircle2 } from "lucide-react";
import { useNavigate } from "react-router-dom";
import MarketChart from "../components/MarketChart";
import OrderBook from "../components/OrderBook";
import { spotTradeApi,userApi } from "../services/api";
const PAIRS=["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT"],DRAFT="vexa_spot_long_term_draft";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
const baseOf=s=>String(s||"").endsWith("USDT")?String(s).slice(0,-4):String(s||"");
const compact=v=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:4});
function Step({n,label,active}){return <div className={"rounded-lg px-2 py-1.5 text-center text-[9px] font-semibold "+(active?"border border-cyan-400/20 bg-cyan-400/10 text-cyan-300":"bg-white/[0.025] text-slate-600")}>{n} · {label}</div>}
function Stat({label,value,tone=""}){return <div className="rounded-xl border border-white/5 bg-[#050812] px-2.5 py-2"><div className="text-[8px] uppercase tracking-wider text-slate-600">{label}</div><div className={"mt-0.5 truncate text-[11px] font-semibold "+tone}>{value}</div></div>}
export default function SpotTradingPage(){
 const dedicatedLongTerm = window.location.pathname.startsWith("/trade/spot/long-term");
 const navigate=useNavigate(),auth=token();
 const [pair,setPair]=useState("BTCUSDT"),[side,setSide]=useState("buy"),[mode,setMode]=useState("quantity"),[quantity,setQuantity]=useState(""),[price,setPrice]=useState(0),[quoteAt,setQuoteAt]=useState(0),[settings,setSettings]=useState(null),[assets,setAssets]=useState([]),[wallet,setWallet]=useState({balance:0}),[orders,setOrders]=useState([]),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const base=baseOf(pair),min=Number(settings?.minOrderUsdt||10),max=Number(settings?.maxOrderUsdt||100000),feeBps=Number(settings?.tradingFeeBps||0),total=Number(quantity||0)*Number(price||0),fee=total*feeBps/10000,payable=side==="buy"?total+fee:Math.max(0,total-fee),pairs=Array.isArray(settings?.supportedPairs)&&settings.supportedPairs.length?settings.supportedPairs:PAIRS;
 const baseBalance=useMemo(()=>{const r=assets.find(a=>String(a?.coin||a?.symbol||"").toUpperCase()===base);return Number(r?.available_balance??r?.availableBalance??r?.balance??0)},[assets,base]);
 const usdtBalance=Number(wallet?.balance||assets.find(a=>String(a?.coin||"").toUpperCase()==="USDT")?.available_balance||0);
 const age=quoteAt?Math.floor((Date.now()-quoteAt)/1000):null,quoteTtl=Number(settings?.quoteTtlSeconds||15),fresh=age!==null&&age<=quoteTtl;
 async function load(){setRefreshing(true);const r=await Promise.allSettled([spotTradeApi.settings(auth),userApi.getUserAssets(auth),userApi.getWalletSummary(auth),spotTradeApi.orders(auth)]);if(r[0].status==="fulfilled")setSettings(r[0].value.data?.data||null);if(r[1].status==="fulfilled")setAssets(Array.isArray(r[1].value.data?.data?.assets)?r[1].value.data.data.assets:Array.isArray(r[1].value.data?.data)?r[1].value.data.data:[]);if(r[2].status==="fulfilled")setWallet(r[2].value.data?.data||{balance:0});if(r[3].status==="fulfilled")setOrders(Array.isArray(r[3].value.data?.data)?r[3].value.data.data:[]);setRefreshing(false)}
 useEffect(()=>{load().finally(()=>setLoading(false))},[auth]);
 useEffect(()=>{let closed=false,ws;try{ws=new WebSocket("wss://stream.binance.com:9443/ws/"+pair.toLowerCase()+"@ticker");ws.onmessage=e=>{try{const p=Number(JSON.parse(e.data)?.c);if(!closed&&p>0){setPrice(p);setQuoteAt(Date.now())}}catch{}};ws.onerror=()=>{if(!closed)setError("Live market stream unavailable. Wait for a fresh quote.")}}catch{setError("Unable to connect to the live market stream.")}return()=>{closed=true;try{ws?.close()}catch{}}},[pair]);
 const setInput=v=>{const clean=String(v||"").replace(/[^0-9.]/g,"");setQuantity(mode==="quantity"?clean:(price?String(Number((Number(clean||0)/price).toFixed(8))):""))};
 const setPercent=p=>{const available=side==="buy"?usdtBalance:baseBalance*price;if(!price||available<=0)return;const quote=Math.min(max,available)*p/100;if(quote<min){setError("Selected amount is below the "+money(min)+" USDT minimum.");return}setQuantity(String(Number((quote/price).toFixed(8))));setError("")};
 const openOrderResult=(order)=>{try{sessionStorage.setItem("vexa_spot_long_term_receipt",JSON.stringify({orderId:order?.id,symbol:order?.symbol,side:order?.side,quantity:order?.quantity,executionPrice:order?.execution_price||order?.executionPrice,quoteAmount:order?.quote_amount||order?.quoteAmount,feeAmount:order?.fee_amount||order?.feeAmount,status:order?.status||"filled",outcome:order?.outcome||null,realizedPnl:order?.realized_pnl??order?.realizedPnl??null,realizedPnlPct:order?.realized_pnl_pct??order?.realizedPnlPct??null,filledAt:order?.filled_at||order?.filledAt||order?.updated_at||order?.created_at}));}catch{}navigate(dedicatedLongTerm?"/trade/spot/long-term/result":"/trade/spot/result")};
 const review=()=>{if(settings?.tradingEnabled===false)return setError(settings?.maintenanceMessage||"Spot / Long-Term trading is currently disabled.");if(side==="buy"&&settings?.buyEnabled===false)return setError("Buy orders are currently disabled.");if(side==="sell"&&settings?.sellEnabled===false)return setError("Sell orders are currently disabled.");if(!fresh)return setError("Live market quote is unavailable or stale. Refresh and try again.");if(!Number(quantity)||total<min)return setError("Minimum order value is "+money(min)+" USDT.");if(total>max)return setError("Maximum order value is "+money(max)+" USDT.");const available=side==="buy"?usdtBalance:baseBalance*price;if(total>available)return setError(side==="buy"?"Insufficient USDT available balance.":"Insufficient asset balance.");sessionStorage.setItem(DRAFT,JSON.stringify({pair,side,quantity,observedPrice:price,quoteAt,createdAt:Date.now()}));setError("");navigate(dedicatedLongTerm ? "/trade/spot/long-term/review" : "/trade/spot/review")};
 if(loading)return <div className="min-h-screen bg-[#050812] p-3 text-slate-300"><div className="mx-auto max-w-6xl rounded-2xl border border-white/10 bg-[#0a0e1a] p-4 text-xs">Loading Spot / Long-Term terminal…</div></div>;
 return <div className="vexa-spot-ui min-h-screen bg-[#050812] p-3 pb-24 text-white sm:p-4 lg:p-5"><div className="mx-auto max-w-7xl space-y-2.5">
  <header className="rounded-2xl border border-white/10 bg-[#0a0e1a]/90 p-3 shadow-[0_12px_35px_rgba(0,0,0,0.2)]">
   <div className="flex items-center justify-between gap-2"><button onClick={()=>navigate("/trade")} className="group flex items-center gap-1 rounded-xl border border-white/10 bg-white/[0.045] px-2.5 py-2 text-[9px] font-semibold text-slate-300 shadow-inner shadow-white/[0.03] transition hover:border-cyan-300/25 hover:bg-cyan-300/10 hover:text-cyan-200 active:scale-[0.98]"><ArrowLeft size={13} className="transition-transform group-hover:-translate-x-0.5"/>Trade</button><button onClick={()=>load()} disabled={refreshing} className="rounded-xl border border-white/10 bg-white/[0.03] p-2 text-slate-400 transition hover:border-cyan-300/20 hover:bg-cyan-300/[0.05] hover:text-cyan-200 active:scale-[0.98]"><RefreshCw size={13} className={refreshing?"animate-spin":""}/></button></div>
   <div className="mt-2 flex flex-wrap items-end justify-between gap-2"><div><div className="text-[9px] uppercase tracking-[0.28em] text-cyan-300">Trade · Spot / Long-Term</div><h1 className="mt-0.5 text-base font-bold sm:text-lg">Market Trading Terminal</h1></div><div className="rounded-full border border-emerald-400/15 bg-emerald-400/5 px-2.5 py-1 text-[9px] text-emerald-300">{settings?.settlementModel==="market_execution"?"Objective market settlement":"Blockchain Ecosystem settlement unavailable"}</div></div>
   <p className="mt-1 text-[9px] leading-4 text-slate-500">Independent spot market execution. Short-Term trading remains on its original terminal and rules.</p>
   <div className="mt-2 grid grid-cols-3 gap-1"><Step n="1" label="Configure" active/><Step n="2" label="Review" /><Step n="3" label="Result" /></div>
  </header>
  <section className="grid gap-2.5 xl:grid-cols-[minmax(0,1.55fr)_minmax(300px,.65fr)]">
   <div className="space-y-2.5">
    <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-2.5">
     <div className="flex items-center justify-between gap-2"><div className="flex items-center gap-2"><select value={pair} onChange={e=>{setPair(e.target.value);setQuantity("");setError("")}} className="rounded-lg border border-white/10 bg-[#050812] px-2.5 py-1.5 text-xs font-bold outline-none">{pairs.map(p=><option key={p}>{p}</option>)}</select><span className="rounded-md bg-white/5 px-1.5 py-1 text-[8px] text-slate-500">MARKET</span></div><div className="text-right"><div className="text-[8px] text-slate-600">LIVE PRICE</div><div className="text-base font-bold tabular-nums">{price?money(price):"Connecting…"}</div><div className={fresh?"text-[8px] text-emerald-300":"text-[8px] text-amber-300"}>{fresh?"● Live · "+age+"s":"○ Waiting for quote"}</div></div></div>
     <div className="mt-2 grid grid-cols-3 gap-1.5"><Stat label="USDT available" value={compact(usdtBalance)} /><Stat label={base+" available"} value={compact(baseBalance)} /><Stat label="Quote TTL" value={(age===null?"—":Math.max(0,quoteTtl-age))+"s left"} tone={fresh?"text-emerald-300":"text-amber-300"}/></div>
     <div className="mt-1.5 rounded-lg border border-cyan-400/10 bg-cyan-400/5 px-2.5 py-2 text-[8px] text-slate-500"><span className="text-cyan-300">Settlement profile:</span> {settings?.activeSettlementProfile?.name||"Default Market Settlement"} · live public market · min {money(min)} / max {money(max)} USDT</div>
     <div className="mt-2 overflow-hidden rounded-xl border border-white/5"><MarketChart symbol={pair} interval="5m" height={245}/></div>
    </section>
    <OrderBook symbol={pair} currentPrice={price}/>
    <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-2.5"><div className="flex items-center gap-1.5 text-[10px] font-semibold"><History size={13} className="text-cyan-300"/>Recent Spot Orders</div><div className="mt-2 space-y-1.5">{orders.length?orders.slice(0,6).map(o=><button key={o.id} type="button" onClick={()=>openOrderResult(o)} className="grid w-full grid-cols-[1fr_auto_auto] items-center gap-2 rounded-lg bg-[#050812] px-2.5 py-2 text-left text-[9px] hover:bg-white/5"><span><b className="text-white">{o.symbol}</b><span className={String(o.side).toLowerCase()==="buy"?"text-emerald-300":"text-red-300"}> · {String(o.side||"").toUpperCase()}</span><span className="ml-1 text-slate-600">#{o.id}</span></span><span className="text-slate-400">{money(o.execution_price||o.executionPrice)}</span><span className="text-emerald-300">{o.status||"filled"}</span></button>):<div className="rounded-lg bg-[#050812] p-3 text-center text-[9px] text-slate-600">No Spot orders yet.</div>}</div><button type="button" onClick={()=>load()} className="mt-2 flex w-full items-center justify-center gap-1 rounded-lg py-1.5 text-[8px] text-cyan-300 transition hover:bg-white/5">Refresh orders <RefreshCw size={10}/></button></section>
   </div>
   <section className="h-fit rounded-2xl border border-white/10 bg-[#0a0e1a] p-2.5 xl:sticky xl:top-3">
    <div className="flex items-center gap-1.5 text-[10px] font-semibold"><BarChart3 size={14} className="text-cyan-300"/>Step 1 · Build Order</div>
    <div className="mt-2 grid grid-cols-2 gap-1 rounded-lg bg-[#050812] p-1"><button onClick={()=>{setSide("buy");setError("")}} className={"rounded-md py-1.5 text-[9px] font-bold transition active:scale-[0.99] "+(side==="buy"?"bg-emerald-400 text-black":"text-slate-500")}>BUY</button><button onClick={()=>{setSide("sell");setError("")}} className={"rounded-md py-1.5 text-[9px] font-bold transition active:scale-[0.99] "+(side==="sell"?"bg-red-400 text-white":"text-slate-500")}>SELL</button></div>
    <div className="mt-2 flex items-center justify-between"><label className="text-[8px] uppercase tracking-wider text-slate-600">{mode==="quantity"?"Quantity ("+base+")":"Order value (USDT)"}</label><div className="flex rounded-md bg-[#050812] p-0.5"><button onClick={()=>setMode("quantity")} className={"rounded px-2 py-1 text-[8px] "+(mode==="quantity"?"bg-white/10 text-white":"text-slate-600")}>Asset</button><button onClick={()=>setMode("quote")} className={"rounded px-2 py-1 text-[8px] "+(mode==="quote"?"bg-white/10 text-white":"text-slate-600")}>USDT</button></div></div>
    <div className="relative mt-1"><input value={mode==="quantity"?quantity:(price?Number((Number(quantity||0)*price).toFixed(2)):"")} onChange={e=>setInput(e.target.value)} inputMode="decimal" placeholder={mode==="quantity"?"0.00000000":"0.00"} className="w-full rounded-lg border border-white/10 bg-[#050812] px-3 py-2 pr-14 text-[13px] font-semibold outline-none focus:border-cyan-400"/><span className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 text-[9px] text-slate-600">{mode==="quantity"?base:"USDT"}</span></div>
    <div className="mt-1.5 grid grid-cols-4 gap-1">{[25,50,75].map(p=><button key={p} onClick={()=>setPercent(p)} disabled={!price} className="rounded-md border border-white/5 bg-white/[0.03] py-1.5 text-[8px] text-slate-400 disabled:opacity-30">{p}%</button>)}<button onClick={()=>setPercent(100)} disabled={!price} className="rounded-md border border-cyan-400/15 bg-cyan-400/5 py-1.5 text-[8px] text-cyan-300 disabled:opacity-30">MAX</button></div>
    <div className="mt-2 rounded-lg border border-white/5 bg-[#050812] p-2.5 space-y-1 text-[9px]"><div className="flex justify-between"><span className="text-slate-600">Order value</span><b>{money(total)} USDT</b></div><div className="flex justify-between"><span className="text-slate-600">Trading fee</span><b>{money(fee)} USDT</b></div><div className="flex justify-between border-t border-white/5 pt-1 font-semibold"><span className="text-slate-500">{side==="buy"?"Estimated debit":"Estimated credit"}</span><b>{money(payable)} USDT</b></div><div className="flex justify-between pt-1 text-[8px] text-slate-700"><span>Min / Max</span><span>{money(min)} / {money(max)} USDT</span></div></div>
    {error&&<div className="mt-2 rounded-lg border border-red-500/15 bg-red-500/10 p-2.5 text-[9px] leading-4 text-red-300">{error}</div>}
    <button onClick={review} disabled={!price||!quantity||settings?.tradingEnabled===false||(side==="buy"&&settings?.buyEnabled===false)||(side==="sell"&&settings?.sellEnabled===false)} className="mt-2 w-full rounded-xl bg-cyan-400 py-2 text-[11px] font-bold text-[#031016] shadow-sm shadow-cyan-400/10 transition active:scale-[0.99] disabled:opacity-35">Review {side==="buy"?"Buy":"Sell"} <ChevronRight size={14} className="ml-1 inline"/></button>
    <div className="mt-2 rounded-lg border border-cyan-400/10 bg-cyan-400/5 p-2.5 text-[8px] leading-4 text-slate-500"><div className="mb-0.5 flex items-center gap-1 text-cyan-300"><ShieldCheck size={11}/>Protected market execution</div>VexaTrade Blockchain Ecosystem · Smart Contract Security · AI Ecosystem verifies the live market context, applicable limits, balance, daily order limit, fee, transaction identity and security framework. One confirmation creates one order.</div>
   </section>
  </section>
  <section className="grid gap-1.5 sm:grid-cols-3"><div className="rounded-xl border border-white/5 bg-[#0a0e1a] p-2.5 text-[9px] text-slate-600"><b className="text-white">01 Configure</b><br/>Pair, side, amount and live quote.</div><div className="rounded-xl border border-white/5 bg-[#0a0e1a] p-2.5 text-[9px] text-slate-600"><b className="text-white">02 Review</b><br/>Chart, order book, price movement and limits.</div><div className="rounded-xl border border-white/5 bg-[#0a0e1a] p-2.5 text-[9px] text-slate-600"><b className="text-white">03 Execute</b><br/>The Vexa Blockchain Ecosystem completes the objective market execution and returns a receipt.</div></section>
  <section className="flex items-start gap-2 rounded-xl border border-amber-400/10 bg-amber-400/5 p-2.5 text-[8px] leading-4 text-slate-500"><Info size={12} className="mt-0.5 shrink-0 text-amber-300"/>Spot / Long-Term is a market product, not a hidden binary outcome contract. P/L is derived from execution price versus later market price within the Vexa Blockchain Ecosystem market and settlement framework.</section>
 </div></div>
}