import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,CheckCircle2,Copy,RefreshCw,Wallet,Activity } from "lucide-react";
import { useNavigate } from "react-router-dom";
import MarketChart from "../components/MarketChart";
import { spotTradeApi,userApi } from "../services/api";
const KEY="vexa_spot_long_term_receipt";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
export default function SpotTradingResultPage(){
 const navigate=useNavigate(),[receipt,setReceipt]=useState(null),[copied,setCopied]=useState(false),[orders,setOrders]=useState([]),[price,setPrice]=useState(0),[assets,setAssets]=useState([]),[settings,setSettings]=useState(null),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const refresh=async()=>{setRefreshing(true);try{const [o,a]=await Promise.allSettled([spotTradeApi.orders(token()),userApi.getUserAssets(token())]);if(o.status==="fulfilled")setOrders(Array.isArray(o.value.data?.data)?o.value.data.data:[]);if(a.status==="fulfilled")setAssets(Array.isArray(a.value.data?.data?.assets)?a.value.data.data.assets:Array.isArray(a.value.data?.data)?a.value.data.data:[])}catch(e){setError(e?.message||"Unable to refresh order data")}finally{setRefreshing(false)}};
 useEffect(()=>{try{const r=JSON.parse(sessionStorage.getItem(KEY)||"null");if(!r){navigate("/trade/spot",{replace:true});return}setReceipt(r)}catch{navigate("/trade/spot",{replace:true})};refresh()},[navigate]);
 useEffect(()=>{spotTradeApi.settings(token()).then(r=>setSettings(r.data?.data||null)).catch(()=>{})},[]);
 useEffect(()=>{if(!receipt?.symbol)return;let closed=false;let ws=null;try{ws=new WebSocket("wss://stream.binance.com:9443/ws/"+String(receipt.symbol).toLowerCase()+"@ticker");ws.onmessage=e=>{try{const p=Number(JSON.parse(e.data)?.c);if(!closed&&p>0)setPrice(p)}catch{}}}catch{}return()=>{closed=true;try{ws?.close()}catch{}}},[receipt]);
 if(!receipt)return <div className="min-h-screen bg-[#050812] p-4 text-white">Loading execution result...</div>;
 const id=receipt.orderId||receipt.id||"—",execution=Number(receipt.executionPrice||receipt.execution_price||0),qty=Number(receipt.quantity||0),side=String(receipt.side||"buy").toLowerCase();
 const unrealized=execution>0&&price>0?(side==="buy"?(price-execution)*qty:(execution-price)*qty):0,unrealizedPct=execution>0&&price>0?(side==="buy"?(price-execution)/execution:(execution-price)/execution)*100:0;
 const base=String(receipt.symbol||"").endsWith("USDT")?String(receipt.symbol).slice(0,-4):"";
 const baseBalance=useMemo(()=>{const row=assets.find(a=>String(a?.coin||a?.symbol||"").toUpperCase()===base);return Number(row?.available_balance??row?.availableBalance??row?.balance??0)},[assets,base]);
 const copy=async()=>{try{await navigator.clipboard.writeText(String(id));setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}};
 return <div className="min-h-screen bg-[#050812] p-2.5 pb-20 text-white sm:p-3"><div className="mx-auto max-w-4xl space-y-2.5">
  <section className="rounded-3xl border border-emerald-400/20 bg-[#0a0e1a] p-5 text-center"><CheckCircle2 className="mx-auto text-emerald-300" size={48}/><div className="mt-2 text-[10px] uppercase tracking-[0.3em] text-emerald-300">Step 3 · Server settled</div><h1 className="mt-1 text-2xl font-bold">Spot Order Filled</h1><p className="mt-1 text-xs text-slate-500">The backend has filled this market order and committed the asset-ledger movement. Spot positions remain open for live market P/L tracking.</p></section>
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-semibold"><Activity size={14} className="text-cyan-300"/>Live position monitor</div><div className="text-right"><div className="text-[9px] text-slate-500">Current market</div><b>{price?money(price):"Connecting..."}</b></div></div><MarketChart symbol={receipt.symbol} interval="5m" height={230}/><div className="mt-2 grid grid-cols-3 gap-2"><div className="rounded-xl bg-[#050812] p-2 text-center"><span className="block text-[9px] text-slate-500">Execution</span><b className="text-xs">{money(execution)}</b></div><div className="rounded-xl bg-[#050812] p-2 text-center"><span className="block text-[9px] text-slate-500">Live P/L</span><b className={"text-xs "+(unrealized>=0?"text-emerald-300":"text-red-300")}>{unrealized>=0?"+":""}{money(unrealized)} USDT</b></div><div className="rounded-xl bg-[#050812] p-2 text-center"><span className="block text-[9px] text-slate-500">Move</span><b className={"text-xs "+(unrealizedPct>=0?"text-emerald-300":"text-red-300")}>{unrealizedPct>=0?"+":""}{unrealizedPct.toFixed(3)}%</b></div></div></section>
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="grid grid-cols-2 gap-3 text-xs"><div><span className="text-slate-500">Pair</span><b className="mt-1 block">{receipt.symbol}</b></div><div><span className="text-slate-500">Side</span><b className="mt-1 block">{side.toUpperCase()}</b></div><div><span className="text-slate-500">Quantity</span><b className="mt-1 block">{receipt.quantity}</b></div><div><span className="text-slate-500">Execution price</span><b className="mt-1 block">{money(execution)}</b></div><div><span className="text-slate-500">Quote amount</span><b className="mt-1 block">{money(receipt.quoteAmount)} USDT</b></div><div><span className="text-slate-500">Status</span><b className="mt-1 block text-emerald-300">{receipt.status||"filled"}</b></div><div><span className="text-slate-500">Current base balance</span><b className="mt-1 block">{money(baseBalance)} {base}</b></div></div><div className="mt-4 flex items-center justify-between rounded-xl bg-[#050812] p-3 text-xs"><span className="text-slate-500">Order ID</span><button onClick={copy} className="flex items-center gap-2 font-semibold">{copied?"Copied":"#"+id}<Copy size={13}/></button></div></section>
  {error&&<div className="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-[11px] text-red-300">{error}</div>}
  <div className="grid grid-cols-2 gap-2"><button onClick={()=>{sessionStorage.removeItem(KEY);navigate("/trade/spot")}} className="rounded-xl bg-cyan-400 py-3 text-sm font-bold text-black"><Wallet className="mr-1 inline" size={15}/>New Order</button><button onClick={()=>navigate("/trade/spot")} className="rounded-xl border border-white/10 py-3 text-sm">Trade Again</button></div>
  <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-4"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">Recent Spot orders</h2><button onClick={refresh} disabled={refreshing} className="flex items-center gap-1 text-[10px] text-cyan-300"><RefreshCw size={12} className={refreshing?"animate-spin":""}/>Refresh</button></div><div className="mt-3 space-y-2">{orders.slice(0,10).map((o,i)=><div key={o.id||i} className="grid grid-cols-[1fr_auto_auto] gap-2 rounded-xl bg-[#050812] p-3 text-[10px]"><span>{o.symbol} · {String(o.side).toUpperCase()}</span><span>{money(o.execution_price||o.executionPrice)}</span><span className="text-emerald-300">{o.status||"filled"}</span></div>)}</div></section>
  <button onClick={()=>navigate("/trade")} className="flex w-full items-center justify-center gap-1 py-2 text-[10px] text-slate-500"><ArrowLeft size={12}/>Back to Trade</button>
 </div></div>;
}