import { useEffect,useMemo,useState } from "react";
import { ArrowLeft,RefreshCw,Wallet,BarChart3,ShieldCheck } from "lucide-react";
import { useNavigate } from "react-router-dom";
import MarketChart from "../components/MarketChart";
import OrderBook from "../components/OrderBook";
import { spotTradeApi,userApi } from "../services/api";
import { useNotification } from "../hooks/useNotification";
const PAIRS=["BTCUSDT","ETHUSDT","SOLUSDT","BNBUSDT","XRPUSDT","DOGEUSDT","ADAUSDT","AVAXUSDT","LINKUSDT"],DRAFT="vexa_spot_long_term_draft";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
const baseOf=s=>String(s||"").endsWith("USDT")?String(s).slice(0,-4):String(s||"");
export default function SpotTradingPage(){
 const navigate=useNavigate(),auth=token(),{showError}=useNotification();
 const [pair,setPair]=useState("BTCUSDT"),[side,setSide]=useState("buy"),[mode,setMode]=useState("quantity"),[quantity,setQuantity]=useState(""),[price,setPrice]=useState(0),[quoteAt,setQuoteAt]=useState(0),[settings,setSettings]=useState(null),[assets,setAssets]=useState([]),[wallet,setWallet]=useState({balance:0}),[loading,setLoading]=useState(true),[refreshing,setRefreshing]=useState(false),[error,setError]=useState("");
 const base=baseOf(pair),min=Number(settings?.minOrderUsdt||10),max=Number(settings?.maxOrderUsdt||100000),feeBps=Number(settings?.tradingFeeBps||0),fee=Number(quantity||0)*Number(price||0)*feeBps/10000,total=Number(quantity||0)*Number(price||0),pairs=Array.isArray(settings?.supportedPairs)&&settings.supportedPairs.length?settings.supportedPairs:PAIRS;
 const baseBalance=useMemo(()=>{const r=assets.find(a=>String(a?.coin||a?.symbol||"").toUpperCase()===base);return Number(r?.available_balance??r?.availableBalance??r?.balance??0)},[assets,base]);
 const usdtBalance=Number(wallet?.balance||assets.find(a=>String(a?.coin||"").toUpperCase()==="USDT")?.available_balance||0);
 const age=quoteAt?Math.floor((Date.now()-quoteAt)/1000):null,quoteTtl=Number(settings?.quoteTtlSeconds||15),fresh=age!==null&&age<=quoteTtl;
 async function load(){setRefreshing(true);const r=await Promise.allSettled([spotTradeApi.settings(auth),userApi.getUserAssets(auth),userApi.getWalletSummary(auth)]);if(r[0].status==="fulfilled")setSettings(r[0].value.data?.data||null);if(r[1].status==="fulfilled")setAssets(Array.isArray(r[1].value.data?.data?.assets)?r[1].value.data.data.assets:Array.isArray(r[1].value.data?.data)?r[1].value.data.data:[]);if(r[2].status==="fulfilled")setWallet(r[2].value.data?.data||{balance:0});setRefreshing(false)}
 useEffect(()=>{load().finally(()=>setLoading(false))},[auth]);
 useEffect(()=>{let closed=false;const ws=new WebSocket("wss://stream.binance.com:9443/ws/"+pair.toLowerCase()+"@ticker");ws.onmessage=e=>{try{const p=Number(JSON.parse(e.data)?.c);if(!closed&&p>0){setPrice(p);setQuoteAt(Date.now())}}catch{}};return()=>{closed=true;try{ws.close()}catch{}}},[pair]);
 const setInput=v=>{const clean=String(v||"").replace(/[^0-9.]/g,"");setQuantity(mode==="quantity"?clean:(price?String(Number((Number(clean||0)/price).toFixed(8))):""))};
 const setPercent=p=>{const available=side==="buy"?usdtBalance:baseBalance*price;if(!price||available<=0)return;const quote=Math.min(max,available)*p/100;if(quote<min){setError("Selected amount is below the "+money(min)+" USDT minimum.");return}setQuantity(String(Number((quote/price).toFixed(8))));setError("")};
 const review=()=>{if(settings?.tradingEnabled===false)return setError(settings?.maintenanceMessage||"Spot / Long-Term trading is currently disabled.");if(side==="buy"&&settings?.buyEnabled===false)return setError("Buy orders are currently disabled.");if(side==="sell"&&settings?.sellEnabled===false)return setError("Sell orders are currently disabled.");if(!fresh)return setError("Live market quote is unavailable or stale. Refresh and try again.");if(!Number(quantity)||total<min)return setError("Minimum order value is "+money(min)+" USDT.");if(total>max)return setError("Maximum order value is "+money(max)+" USDT.");const available=side==="buy"?usdtBalance:baseBalance*price;if(total>available)return setError(side==="buy"?"Insufficient USDT available balance.":"Insufficient asset balance.");sessionStorage.setItem(DRAFT,JSON.stringify({pair,side,quantity,observedPrice:price,quoteAt,createdAt:Date.now()}));setError("");navigate("/trade/spot/review")};
 if(loading)return <div className="min-h-screen bg-[#050812] p-4 text-slate-300"><div className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-4 text-sm">Loading Spot / Long-Term trading...</div></div>;
 return <div className="min-h-screen bg-[#050812] p-3 pb-24 text-white sm:p-4"><div className="mx-auto max-w-6xl space-y-3">
 <header className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><button onClick={()=>navigate("/trade")} className="mb-2 flex items-center gap-1 text-[10px] text-slate-500"><ArrowLeft size={12}/>Trade</button><div className="text-[10px] uppercase tracking-[0.28em] text-cyan-300">Trade · Spot / Long-Term</div><h1 className="mt-1 text-lg font-bold">Market Trading Terminal</h1><p className="mt-1 text-[10px] leading-4 text-slate-500">Buy or sell supported assets at the server live market price. Existing Short-Term trading remains unchanged.</p><div className="mt-3 grid grid-cols-3 gap-1.5 text-center text-[9px] uppercase tracking-wider"><div className="rounded-xl border border-cyan-400/20 bg-cyan-400/5 p-2 text-cyan-300">1 · Configure</div><div className="rounded-xl bg-[#050812] p-2 text-slate-600">2 · Review</div><div className="rounded-xl bg-[#050812] p-2 text-slate-600">3 · Result</div></div></header>
 <section className="grid gap-3 lg:grid-cols-[1.35fr_.65fr]"><div className="space-y-3"><section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex items-center justify-between"><select value={pair} onChange={e=>{setPair(e.target.value);setQuantity("");setError("")}} className="rounded-xl border border-white/10 bg-[#050812] px-3 py-2 text-sm font-bold">{pairs.map(p=><option key={p}>{p}</option>)}</select><div className="text-right"><div className="text-[9px] text-slate-500">Live market price</div><div className="text-lg font-bold">{price?money(price):"Connecting..."}</div><div className={fresh?"text-[9px] text-emerald-300":"text-[9px] text-amber-300"}>{fresh?"Live · "+age+"s ago":"Waiting for live quote"}</div></div></div><div className="mt-3"><MarketChart symbol={pair} interval="5m" height={250}/></div></section><OrderBook symbol={pair} currentPrice={price}/></div>
 <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex items-center gap-2 text-xs font-semibold"><BarChart3 size={15} className="text-cyan-300"/>Step 1 · Build Order</div><div className="mt-3 grid grid-cols-2 gap-1 rounded-xl bg-[#050812] p-1"><button onClick={()=>setSide("buy")} className={"rounded-lg py-2.5 text-xs font-bold "+(side==="buy"?"bg-emerald-400 text-black":"text-slate-400")}>Buy</button><button onClick={()=>setSide("sell")} className={"rounded-lg py-2.5 text-xs font-bold "+(side==="sell"?"bg-red-400 text-white":"text-slate-400")}>Sell</button></div>
 <div className="mt-3 grid grid-cols-2 gap-2"><div className="rounded-xl bg-[#050812] p-2"><div className="text-[9px] text-slate-500">USDT available</div><b className="text-xs">{money(usdtBalance)}</b></div><div className="rounded-xl bg-[#050812] p-2"><div className="text-[9px] text-slate-500">{base} available</div><b className="text-xs">{money(baseBalance)}</b></div></div>
 <div className="mt-3 flex items-center justify-between"><label className="text-[10px] uppercase tracking-wider text-slate-500">{mode==="quantity"?"Quantity ("+base+")":"Order value (USDT)"}</label><div className="flex rounded-lg bg-[#050812] p-1"><button onClick={()=>setMode("quantity")} className={"px-2 py-1 text-[9px] "+(mode==="quantity"?"bg-white/10 text-white":"text-slate-500")}>Quantity</button><button onClick={()=>setMode("quote")} className={"px-2 py-1 text-[9px] "+(mode==="quote"?"bg-white/10 text-white":"text-slate-500")}>USDT</button></div></div>
 <input value={mode==="quantity"?quantity:(price?Number((Number(quantity||0)*price).toFixed(2)):"")} onChange={e=>setInput(e.target.value)} inputMode="decimal" placeholder="0.00" className="mt-1 w-full rounded-xl border border-white/10 bg-[#050812] px-3 py-3 text-sm outline-none focus:border-cyan-400"/><div className="mt-2 grid grid-cols-4 gap-1">{[25,50,75].map(p=><button key={p} onClick={()=>setPercent(p)} disabled={!price} className="rounded-lg border border-white/10 bg-white/5 py-2 text-[10px] disabled:opacity-40">{p}%</button>)}<button onClick={()=>setPercent(100)} disabled={!price} className="rounded-lg border border-cyan-400/20 bg-cyan-400/5 py-2 text-[10px] text-cyan-300 disabled:opacity-40">Max</button></div>
 <div className="mt-3 space-y-1 text-xs"><div className="flex justify-between"><span className="text-slate-500">Estimated order value</span><b>{money(total)} USDT</b></div><div className="flex justify-between"><span className="text-slate-500">Trading fee</span><b>{money(fee)} USDT</b></div><div className="flex justify-between"><span className="text-slate-500">Estimated debit/credit</span><b>{money(side==="buy"?total+fee:total-fee)} USDT</b></div></div><div className="mt-1 flex justify-between text-[9px] text-slate-600"><span>Minimum / Maximum</span><span>{money(min)} / {money(max)} USDT</span></div>{error&&<div className="mt-3 rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-[11px] text-red-300">{error}</div>}
 <button onClick={review} disabled={!price||!quantity||settings?.tradingEnabled===false||(side==="buy"&&settings?.buyEnabled===false)||(side==="sell"&&settings?.sellEnabled===false)} className="mt-4 w-full rounded-2xl bg-cyan-400 py-3 text-sm font-bold text-black disabled:opacity-40">Review {side==="buy"?"Buy":"Sell"} Order</button><div className="mt-3 rounded-xl border border-cyan-400/10 bg-cyan-400/5 p-3 text-[10px] leading-4 text-slate-500"><div className="flex items-center gap-1 text-cyan-300"><ShieldCheck size={13}/>Execution & settlement protection</div>Live quote age, account balance, configured limits, daily order limit, buy/sell availability, server-side price validation and transaction security are checked before settlement. Spot settlement is market-based: there is no hidden per-user WIN/LOSS override. {feeBps>0?`Current fee: ${feeBps} bps.`:"No trading fee is currently configured."}</div></section></section>
 <section className="grid gap-2 sm:grid-cols-3"><div className="rounded-xl bg-[#0a0e1a] p-3 text-[10px] text-slate-500"><Wallet size={14} className="mb-1 text-cyan-300"/><b className="text-white">1. Configure</b><br/>Choose pair, Buy/Sell and amount.</div><div className="rounded-xl bg-[#0a0e1a] p-3 text-[10px] text-slate-500"><b className="text-white">2. Review</b><br/>Inspect live chart, quote, limits and balances.</div><div className="rounded-xl bg-[#0a0e1a] p-3 text-[10px] text-slate-500"><b className="text-white">3. Execute</b><br/>One confirmation creates one idempotent market order.</div></section>
 </div></div>
}