import { useEffect,useState } from "react";
import { CheckCircle2,Copy,History,Wallet } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { tradeApi } from "../../../services/api";
import TradeSectionLayout from "../TradeSectionLayout";
const KEY="vexa_short_term_receipt";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
const money=v=>Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:8});
const outcomeOf=t=>String(t?.result||t?.status||"").toLowerCase();
const profitOf=t=>{const o=outcomeOf(t),a=Number(t?.amount||0),p=Number(t?.payout_percent||t?.payoutPercent||0);if(o==="win")return a*p/100;if(o==="loss")return -a;return 0};
export default function ShortTermResultPage(){
 const navigate=useNavigate();const[receipt,setReceipt]=useState(null),[copied,setCopied]=useState(false),[loading,setLoading]=useState(true);
 useEffect(()=>{try{const r=JSON.parse(sessionStorage.getItem(KEY)||"null");if(r){setReceipt(r);setLoading(false);return}}catch{};let cancelled=false;const load=async()=>{try{const r=await tradeApi.history(token());const rows=Array.isArray(r.data?.data)?r.data.data:[];const first=rows.find(x=>["win","loss","tie","completed","settled"].includes(outcomeOf(x)));if(!cancelled&&first){setReceipt(first);sessionStorage.setItem(KEY,JSON.stringify(first))}}finally{if(!cancelled)setLoading(false)}};void load();return()=>{cancelled=true}},[]);
 if(loading)return <TradeSectionLayout title="Settlement Receipt" subtitle="Loading final result" mode="short"><div className="rounded-2xl bg-[#0a0e1a] p-4 text-xs text-slate-400">Loading final WIN/LOSS receipt…</div></TradeSectionLayout>;
 if(!receipt)return <TradeSectionLayout title="Settlement Receipt" subtitle="No receipt available" mode="short"><div className="rounded-2xl bg-[#0a0e1a] p-4 text-xs text-slate-400">The settlement receipt is not available yet. <button className="text-cyan-300" onClick={()=>navigate("/trade/short-term/history")}>Open history</button></div></TradeSectionLayout>;
 const o=outcomeOf(receipt),profit=profitOf(receipt),win=o==="win",loss=o==="loss",id=receipt.id||"—";
 const copy=async()=>{try{await navigator.clipboard.writeText(String(id));setCopied(true);setTimeout(()=>setCopied(false),1200)}catch{}};
 return <TradeSectionLayout title="Settlement Receipt" subtitle="Final Short-Term WIN / LOSS result" mode="short"><div className="mx-auto max-w-2xl space-y-2.5">
 <section className={`rounded-3xl border p-5 text-center ${win?"border-emerald-300/20 bg-emerald-300/10":loss?"border-red-300/20 bg-red-300/10":"border-white/10 bg-[#0a0e1a]"}`}><CheckCircle2 className="mx-auto text-cyan-300" size={44}/><div className="mt-2 text-[9px] uppercase tracking-[.3em] text-slate-400">FINAL SETTLEMENT</div><h1 className={`mt-1 text-3xl font-bold ${win?"text-emerald-300":loss?"text-red-300":"text-white"}`}>{o?o.toUpperCase():"SETTLED"}</h1><div className="mt-2 text-sm font-semibold">{profit>=0?"+":""}{money(profit)} USDT</div></section>
 <section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3 text-xs"><div className="grid grid-cols-2 gap-3"><div><span className="text-slate-600">Pair</span><b className="mt-1 block">{receipt.pair||"—"}</b></div><div><span className="text-slate-600">Direction</span><b className="mt-1 block">{String(receipt.direction||"").toUpperCase()}</b></div><div><span className="text-slate-600">Stake</span><b className="mt-1 block">{money(receipt.amount)} USDT</b></div><div><span className="text-slate-600">Entry</span><b className="mt-1 block">{money(receipt.entry_price||receipt.entryPrice)}</b></div><div><span className="text-slate-600">Exit</span><b className="mt-1 block">{money(receipt.exit_price||receipt.exitPrice||receipt.settlement_price||receipt.settlementPrice)}</b></div><div><span className="text-slate-600">Payout</span><b className="mt-1 block">{money(receipt.payout_percent||receipt.payoutPercent)}%</b></div><div><span className="text-slate-600">Status</span><b className="mt-1 block">{String(receipt.status||o).toUpperCase()}</b></div><div><span className="text-slate-600">Order ID</span><button onClick={copy} className="mt-1 flex items-center gap-1 font-semibold">#{id} <Copy size={12}/>{copied?" Copied":""}</button></div></div></section>
 <div className="grid grid-cols-2 gap-2"><button onClick={()=>{sessionStorage.removeItem(KEY);navigate("/trade/short-term/trade")}} className="rounded-xl bg-cyan-400 py-3 text-sm font-bold text-black"><Wallet className="mr-1 inline" size={15}/>New Trade</button><button onClick={()=>navigate("/trade/short-term/history")} className="rounded-xl border border-white/10 py-3 text-sm"><History className="mr-1 inline" size={15}/>History</button></div>
 </div></TradeSectionLayout>;
}