import { useEffect,useState } from "react";
import { History, RefreshCw } from "lucide-react";
import { tradeApi } from "../../../services/api";
import TradeSectionLayout from "../TradeSectionLayout";
const token=()=>localStorage.getItem("userToken")||localStorage.getItem("token")||localStorage.getItem("accessToken")||"";
export default function ShortTermHistoryPage(){
 const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=async()=>{setLoading(true);try{const r=await tradeApi.history(token());setRows(Array.isArray(r.data?.data)?r.data.data:[]);setError("")}catch(e){setError(e?.message||"Unable to load trade history")}finally{setLoading(false)}};
 useEffect(()=>{load();const id=setInterval(load,30000);return()=>clearInterval(id)},[]);
 return <TradeSectionLayout title="Trade History" subtitle="Completed Short-Term settlements" mode="short"><section className="rounded-2xl border border-white/10 bg-[#0a0e1a] p-3"><div className="flex items-center justify-between"><div className="flex items-center gap-2 text-xs font-semibold"><History size={15} className="text-cyan-300"/>History</div><button onClick={load} disabled={loading} className="rounded-lg border border-white/10 p-2 text-slate-400"><RefreshCw size={13} className={loading?"animate-spin":""}/></button></div>{error&&<div className="mt-3 rounded-xl bg-red-500/10 p-3 text-[10px] text-red-300">{error}</div>}<div className="mt-3 space-y-2">{!loading&&!rows.length&&<div className="py-10 text-center text-[10px] text-slate-600">No completed trades yet.</div>}{rows.map((r,i)=>{const result=String(r.result||r.status||"").toUpperCase();const tone=result==="WIN"?"text-emerald-300":result==="LOSS"?"text-red-300":result==="TIE"?"text-amber-300":"text-slate-300";return <div key={r.id||i} className="grid grid-cols-[1fr_auto] gap-2 rounded-xl bg-[#050812] p-3 text-[10px]"><div><div className="font-semibold">{r.pair||"—"} · {String(r.direction||r.side||"").toUpperCase()}</div><div className="mt-1 text-slate-500">{r.created_at||r.updated_at||"—"}</div></div><div className={"text-right font-bold "+tone}>{result||"—"}<div className="mt-1 font-normal text-slate-500">{r.amount||"0"} USDT</div></div></div>})}</div></section></TradeSectionLayout>;
}